### PR TITLE
[draft] fix build issue caused by build-helper

### PR DESCRIPTION
**Pull request by gayanper**
## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by gayanper** [comment]
@iloveeclipse Not sure if this will happen on jenkins since we might have proxy maven repo. But when I was trying build against central repo with a clean local repository i continuously got 

```
Error:  Plugin org.codehaus.mojo:build-helper-maven-plugin:3.3.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:build-helper-maven-plugin:jar:3.3.0: 1 problem was encountered while building the effective model
Error:  [FATAL] Non-parseable POM /home/runner/.m2/repository/org/codehaus/mojo/build-helper-maven-plugin/3.3.0/build-helper-maven-plugin-3.3.0.pom: UTF-8 BOM plus xml decl of ISO-8859-1 is incompatible (position: START_DOCUMENT seen <?xml version="1.0" encoding="ISO-8859-1"... @1:42)  @ line 1, column 42
```

from batch compiler module. Upgrading to latest version fixed it. Let me know what you think

**Comment by iloveeclipse** [comment]
@gayanper : I have zero knowledge about maven. @merks may be?

**Comment by merks** [comment]
I can't see any harm in using a newer version if that solves some problem.  I would be nice to know which file has this problem because it does seem wrong to have a BOM in a file encoded with ISO-8859-1...

**Comment by akurtakov** [comment]
This has been fixed via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1392 .

**Pull request closed without merging**
