### PR TITLE
Completion for unimported types doesn't work

### LINKED ISSUE #1502: Completion for unimported types doesn't work
The related issue - https://github.com/redhat-developer/vscode-java/issues/1123

Steps to reproduce:
- create the following class
```
public class X {
	void foo() {
		new ArrayList<>().|
	}
}
```
- call CA

### PR DESCRIPTION
**Pull request by snjeza**
Fixes #1502

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
Found this only after commenting in #1502 - still a few answers to my questions there would help the reviewer :)

**Comment by akurtakov** [comment]
Are @snjeza 's answers on the issue good?

**Comment by jukzi** [comment]
@snjeza please resolve conflicts and update the commit message to reflect the change and and contain a reference to the bug

**Comment by jukzi** [comment]
LGTM, and it usefull. i tested it. It could be improved, please:
```
package aaa;

import java.util.ArrayList;

public class X {
	void foo() {
		new ArrayList<>().add(null);
		new HashMap().cl|
		}
}
```
image
results in not compile-able completion:
`new HashMap<K, V>().clear();`

it would be better if it completes to diamond operator `new HashMap<>().clear();` as K and V are not defined.

**Comment by snjeza** [comment]
> results in not compile-able completion:
new HashMap<K, V>().clear();
it would be better if it completes to diamond operator new HashMap<>().clear(); as K and V are not defined.

This should be resolved in [eclipse.jdt.ui](https://github.com/eclipse-jdt/eclipse.jdt.ui) - https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/a4c1b5bc5dbb294e8c23b93296effeb1d5c2cae0/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaMethodCompletionProposal.java#L474

**Comment by rgrunber** [comment]
> > results in not compile-able completion:
> > new HashMap<K, V>().clear();
> > it would be better if it completes to diamond operator new HashMap<>().clear(); as K and V are not defined.
> 
> This should be resolved in [eclipse.jdt.ui](https://github.com/eclipse-jdt/eclipse.jdt.ui) - https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/a4c1b5bc5dbb294e8c23b93296effeb1d5c2cae0/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaMethodCompletionProposal.java#L474

Looks to still be an issue for me with this PR on latest master of jdt.core and latest jdt.ui.

hashmap-clear-generics

**Comment by stephan-herrmann** [comment]
> > > results in not compile-able completion:
> > > new HashMap<K, V>().clear();
> > > it would be better if it completes to diamond operator new HashMap<>().clear(); as K and V are not defined.
> > 
> > 
> > This should be resolved in [eclipse.jdt.ui](https://github.com/eclipse-jdt/eclipse.jdt.ui) - https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/a4c1b5bc5dbb294e8c23b93296effeb1d5c2cae0/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaMethodCompletionProposal.java#L474
> 
> Looks to still be an issue for me with this PR on latest master of jdt.core and latest jdt.ui.

I guess `JavaMethodCompletionProposal` is good, but perhaps somewhere in the implementation of `canUseDiamon()` this situation is handled wrongly. In particular `InternalExtendedCompletionContext.canUseDiamond(String[], char[][])` from https://bugs.eclipse.org/578969 has a suspicious comment:
```
// If no LHS or return type expected, then we can safely use diamond
```

No LHS is actually the situation mentioned by @jukzi , and for this very reason a diamond is illegal.

**Comment by datho7561** [comment]
Roland sent me to this PR, since I took a look at another PR related to generics. Taking a look at this, it seems like there are two possible ways forward for the completion Stephan mentioned:
- substitute the erasure of the type variables for the type variables (eg. `HashMap<Object, Object>` in this case)
- use the raw type (i.e. `HashMap` with no diamond operator and no type arguments passed)

However, from my understanding, these fixes to completion seem unrelated to the changes in this PR. Is there anything blocking this PR from being merged?

**Pull request merged**
