### PR TITLE
[23] JEP 476: Module Import Declarations (Preview)

### LINKED ISSUE #2383: [23] JEP 476: Module Import Declarations (Preview)
From the JEP - "Enhance the Java programming language with the ability to succinctly import all of the packages exported by a module."

More details here - https://openjdk.org/jeps/476

### PR DESCRIPTION
**Pull request by stephan-herrmann**
fixes #2383

Code changes:
+ grammar & scanner
   + scanner to detect keyword module in "import module foo", but not in "import module.foo"
+ resolving
+ basic errors
+ implement ModuleBinding.reads() as reflexive property

Aspects covered during resolution:
+ shadowing
+ ambiguity
   + module vs package
   + module vs. other module
   + packages of the same module (direct or via requires transitive)
+ accessibility
+ packages from requires transitive
+ redundant imports (flag as unused)
+ module import in CU in unnamed module

Tests:
+ pull up reusable methods to new AbstractModuleCompilationTest
+ for tests using writeFileCollecting ensure shouldFlush*=false

Back to back comparison with javac:
+ evaluation of run.javac improved for runConformModuleTest()
+ excuse for javac not considering reflexive 'reads' (as of 23 ea build 24 - fixed just now)
+ adjust ModuleCompilationTests.testReleaseOption15: new javac warning

Convenience for test implementation:
+ stop suggesting string-concatenation as cut-n-paste test results

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
@mpalat while this is still a draft, you're already invited to give a first review, specifically because this is my first PR for [23] and I may not be up-to-date regarding the process for beta preview features :smile:

**Comment by jarthana** [comment]
I am going to work on top of this PR for issue #2474 . If I come across anything worthwhile sharing, will do so.

**Comment by jarthana** [comment]
@stephan-herrmann , the changes look OK to me. I have been working on issue #2474 with these changes and found no issue so far. Would you mind if I went ahead and merged this PR? If anything, we can take it up along the way. We still have time for Java 23.

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann , the changes look OK to me. I have been working on issue #2474 with these changes and found no issue so far. Would you mind if I went ahead and merged this PR? If anything, we can take it up along the way. We still have time for Java 23.

Thanks, Jay.

Feel free to resolve conflicts now, or let me do it later today.

**Comment by jarthana** [comment]
> Feel free to resolve conflicts now, or let me do it later today.

I just used the webeditor and resolved (first time). Let's wait for the tests to complete and will release.

**Comment by stephan-herrmann** [comment]
> > Feel free to resolve conflicts now, or let me do it later today.
> 
> I just used the webeditor and resolved (first time). Let's wait for the tests to complete and will release.

thanks, let's call that a near miss :)

Remaining problem (after fixing the merge bug):
> 00:24:04  [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.8:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jdt.apt.core: Baseline and reactor have the same fully qualified version, but different content

**Comment by jarthana** [comment]
> Remaining problem (after fixing the merge bug):
> 
> > 00:24:04  [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.8:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jdt.apt.core: Baseline and reactor have the same fully qualified version, but different content

I have no clue why this would come up. Can we touch the apt.core and move, perhaps? :)

**Comment by stephan-herrmann** [comment]
> > Remaining problem (after fixing the merge bug):
> > > 00:24:04  [ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.8:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jdt.apt.core: Baseline and reactor have the same fully qualified version, but different content
> 
> I have no clue why this would come up. Can we touch the apt.core and move, perhaps? :)

In master this plugin was bumped up to 3.8.500 whereas the beta branch still has 3.8.400.

Updating the version in the beta branch will create a merge conflict wrt master.

The version bump happened in commit 3906e0031493114e0dcc2c58f40f32aadd030ba0 which seems to be from #2531.

@jarthana what is your rhythm for master to beta merges? Should we do one right now to align versions?

@akurtakov it seems you merged #2531 without squashing. Was that by intention? The downside is that none of the commit comments carry any context like link to issue or PR. Just now I found that github still "knows" about the connection, but when looking at those commits in Eclipse there is no context at all, which is bad I think.

**Comment by akurtakov** [comment]
@stephan-herrmann The reason to not squash version bump with the rest is that this makes cherry-picking a change (without playing with version - which is different for each branch anyway) a direct one.

**Comment by akurtakov** [comment]
> > @stephan-herrmann The reason to not squash version bump with the rest is that this makes cherry-picking a change (without playing with version - which is different for each branch anyway) a direct one.
> 
> @akurtakov I wasn't aware of any scenarios where cherry-pick is used in this repo (I assume you're thinking of some maintenance branch, perhaps in some fork?). 

I'm following the same procedure as for Platform (https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-a-pull-request point 3. ) as it is not contradicting JDT's one (https://github.com/eclipse-jdt/.github/blob/main/CONTRIBUTING.md#reviewing-a-change) allowing rebase and merge. 
I used it in jdt.core (https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2375) and jdt.ui does it (https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/472/commits) and following the same practice for whole of JDT sounds good idea to me.


> Can you recommend a gesture for navigating from a commit in Eclipse to the corresponding PR?

Other than using the commit sha in github web and search for it - no. Do you rely on full urls in the commit message somehow? I can't navigate straight from Eclipse from e.g. a8bb9ad04a8363e60b2badb7b2f14499302ce8ca, 18fdf9db70607b2073b06ed872af4075f8337c50, 8e7bc9c01116cebd5c5cd36198d0accb1dbaa6f4 ,  3057b7b9f31d9b397d7dd8855fee9f85d199169c, c6b3f6dc1830476552509a82ac1d19738c66ff0c and many others. 

> 
> Thinking more about it, cherry-picking _only the version bump_ seems to do the trick here, as git now understands that we already have this change and will not signal a conflict during the next merge.

Having actual change and version bump being on separate commits has proven itself over the years in many cases to ease working with branches.

**Comment by jarthana** [comment]
> @jarthana what is your rhythm for master to beta merges? Should we do one right now to align versions?

We have been more regular with jdt.core than the other two projects. I thought @mpalat did this just last week. I wonder if something was missed.

**Comment by stephan-herrmann** [comment]
> > > @stephan-herrmann The reason to not squash version bump with the rest is that this makes cherry-picking a change (without playing with version - which is different for each branch anyway) a direct one.
> > 
> > 
> > @akurtakov I wasn't aware of any scenarios where cherry-pick is used in this repo (I assume you're thinking of some maintenance branch, perhaps in some fork?).
> 
> I'm following the same procedure as for Platform (https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-a-pull-request point 3. ) as it is not contradicting JDT's one (https://github.com/eclipse-jdt/.github/blob/main/CONTRIBUTING.md#reviewing-a-change) allowing rebase and merge. I used it in jdt.core (#2375) and jdt.ui does it (https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/472/commits) and following the same practice for whole of JDT sounds good idea to me.

That doesn't explain the relevance of cherry-pick :)  but I'm not arguing against non-squashed merges per-se. Perhaps in that case we should just more carefully respect that other rule:

> Commit Message Recommendations:
> `<issue title> #<issue number>`

**Comment by iloveeclipse** [comment]
> Do you rely on full urls in the commit message somehow? I can't navigate straight from Eclipse from e.g. https://github.com/eclipse-jdt/eclipse.jdt.core/commit/a8bb9ad04a8363e60b2badb7b2f14499302ce8ca, https://github.com/eclipse-jdt/eclipse.jdt.core/commit/18fdf9db70607b2073b06ed872af4075f8337c50, https://github.com/eclipse-jdt/eclipse.jdt.core/commit/8e7bc9c01116cebd5c5cd36198d0accb1dbaa6f4 , https://github.com/eclipse-jdt/eclipse.jdt.core/commit/3057b7b9f31d9b397d7dd8855fee9f85d199169c, https://github.com/eclipse-jdt/eclipse.jdt.core/commit/c6b3f6dc1830476552509a82ac1d19738c66ff0c and many others.

Yes! Given full ticket url in the commit message, one can navigate to that ticket directly from Git History view.
To be more clear, I've updated https://github.com/eclipse-jdt/.github/blob/main/CONTRIBUTING.md#commit-message-recommendations to match https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#commit-message-recommendations. Nothing new there.

**Comment by stephan-herrmann** [comment]
Superseded by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2550

**Pull request closed without merging**
