### PR TITLE
Releng jenkins improvements

### PR DESCRIPTION
**Pull request by akurtakov**
## What it does
Removes weird cobol warnings report and moves to Java 17 Temurin distro for the build so it's actually 17.0.6

## How to test
Verification build still succeeds

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by laeubi** [comment]
Maybe JDT can also use checks plugin https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2050

**Comment by akurtakov** [comment]
This is smth for JDT committers to decide. What I try here is to keep the builds sane at least. The opportunities to improve on current state are huge.

**Comment by akurtakov** [comment]
This would require the plugin being enabled on JDT JIPP for which we would need JDT lead to open helpdesk issue if wanted.

**Comment by iloveeclipse** [comment]
> Maybe JDT can also use checks plugin https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2050

I've read the ticket but I have no clue what it is supposed to do. Any **concrete** example?

> This would require the plugin being enabled on JDT JIPP for which we would need JDT lead to open helpdesk issue if wanted.

Once I understood the answer for question above I could do that. I believe accucobol thing was added because no one asked that question upfront :-(

**Comment by akurtakov** [comment]
This one seems ready to go. Using checks plugin should be handled by dedicated issue/pr.

**Comment by laeubi** [comment]
> 've read the ticket but I have no clue what it is supposed to do. Any **concrete** example?

First step is to copy the ticket text and replace "platform" with "jdt" and open a help-desk ticket, and one needs +1 from project lead.

If this is done, one needs to adjust the buildjob and then gets the metrics published to the PR as well as seen here:
grafik

**Comment by iloveeclipse** [comment]
Sorry what *exactly* be *added*? Test results we have on jenkins, eca is checked already.
Do you mean "Code Analysis"? Can you give a link with concrete results where it is already done?

**Comment by laeubi** [comment]
It adds the result of all enabled "checks" (in this case Code Analysis + tests) so you get all infos (e.g. newly introduced warnings) in Github directly, this is used for example in Equinox here you see checks for javadoc, warnings, ... (just scroll down the list a bit): https://github.com/eclipse-equinox/equinox/pull/199

**Comment by laeubi** [comment]
In the Jenkins job config:
grafik

in the Jenkinsfile:
https://github.com/eclipse-platform/eclipse.platform/commit/f9dad3eba972aaf686e54816e06659db1293ad78

**Pull request merged**
