### PR TITLE
[Build] Remove obsolete build-scripts for ubunut-jikespg docker image

### PR DESCRIPTION
**Pull request by HannesWell**
## What it does
With https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2271 the removed scripts are not necessary anymore.

But in general I wonder if the build docker-image is even used at all? I could not find any references in the current build setup of JDT.
Unfortunately I also could not find the current number of recent pulls in Docker-Hub:
- https://hub.docker.com/layers/eclipse/platformreleng-ubuntu-gtk3-metacity/jikespg/images/sha256-1579f6b3286aca655e20c2dedf22d4eb38254ad413594c49093b61fb0f0857ad?context=explore

@akurtakov, @iloveeclipse, @jarthana or @sravanlakkimsetti could you help here or could tell who knows this?

## Author checklist

- [ ] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
The history of those files points to https://bugs.eclipse.org/576415

The background is this: generating our parser from the grammar file `java.g` involves an invocation of the parser generator `jikespg`, as explained in a bit detail on https://github.com/eclipse-jdt/eclipse.jdt.core/wiki/ECJ-Parse

Over time we had to fix a few bugs in that tool, as can be seen in https://github.com/jikespg/jikespg/tree/fixes-combined - Unfortunately, compiling this C program doesn't seem to be straight forward on windows machines. So when I change the grammar, I have no problem generating the parser (as I'm on linux), but @mpalat e.g. had issues with that.

Ergo, Manoj will tell you, if the solution with parser-generator-as-a-service has been used recently. Look at the [history of java.g](https://github.com/eclipse-jdt/eclipse.jdt.core/commits/master/org.eclipse.jdt.core.compiler.batch/grammar/java.g) to find out who changed the grammar file in the past. All of them needed to invoke jikespg one way or other. @srikanth-sankaran  I believe you have a recent / functioning jikespg on your machine, right?

**Comment by srikanth-sankaran** [comment]
I am in windows generally but use a Ubuntu VM for running jikespg.

**Comment by mpalat** [comment]
> Ergo, Manoj will tell you, if the solution with parser-generator-as-a-service has been used recently. Look at the [history of java.g](https://github.com/eclipse-jdt/eclipse.jdt.core/commits/master/org.eclipse.jdt.core.compiler.batch/grammar/java.g) to find out who changed the grammar file in the past. All of them needed to invoke jikespg one way or other. @srikanth-sankaran I believe you have a recent / functioning jikespg on your machine, right?

I still use the RAW version and I don't use this service. I use an Ubuntu VM and then do the scp.  However, script enabled people to onboard faster(especially if one is not familiar with UNIX world).  That should stay. I will have to request the author of this setup, @sravanlakkimsetti to chime in here for an authoritative answer about deletion.

**Comment by jarthana** [comment]
I still use the job that's here - https://ci.eclipse.org/jdt/job/eclipse.jdt.core-jikespg-gerrit/ to run the parser generator.

**Comment by sravanlakkimsetti** [comment]
jikespg image was created for  https://ci.eclipse.org/jdt/job/eclipse.jdt.core-jikespg-gerrit/ only. If this job is not being used anymore we can go ahead with the deletion. Since @jarthana confirmed that he is still using this job lets keep it.

**Comment by akurtakov** [comment]
I'm closing this pull request in this case.

**Comment by akurtakov** [comment]
It's good idea to update the dockerfile/image to supported Ubuntu version though.

**Pull request closed without merging**
