### PR TITLE
List of patterns in case statements

### LINKED ISSUE #1643: JEP 443: lists of patterns as a case label
i.e.

```java
record Box<T extends Ball>(T content) { }

sealed abstract class Ball permits RedBall, BlueBall, GreenBall { }
final  class RedBall   extends Ball { }
final  class BlueBall  extends Ball { }
final  class GreenBall extends Ball { }

public class A {
    public static void main(String... args) {
        Box box = null;
        switch (box) {
        case Box(RedBall _), Box(BlueBall _) when args.length == 4:
            System.out.println("hello");
            break;
        default:
            System.out.println("goodbye");
        }
    }
}
```

see the discussion here: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1517#issuecomment-1829038759

### PR DESCRIPTION
**Pull request by datho7561**
- Parse multiple Patterns in a case statement
- AST & generator changes for list of patterns
- Fix error reporting for a pattern variable + multiple patterns

Closes #1643

## What it does

Parse case statements with multiple patterns, as per JEP 443.

## How to test

Confirm the following code snippet compiles and executes as expected:

```java
Object o = "Hello, World";
switch (o) {
case String _, List _ when 1 == 1: System.out.println("it's working"); break;
default: System.out.println("it's not working");
}
```

Confirm that errors are placed on `a` and `b` in the following snippet:

```java
Object o = "Hello, World";
switch (o) {
case String a, List b when 1 == 1: System.out.println("it's working"); break;
default: System.out.println("it's not working");
}
```

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by datho7561** [comment]
Seems like `when` clauses and empty record patterns (i.e. `MyRecord()`) are broken and causing test failures

**Comment by datho7561** [comment]
Do we care about the test failure? I'm not sure what it's trying to test. The following code doesn't compile:

```java
class SwitchCompletion {
	public static void main(String... args) {
		int i =  0;
		switch (i) {
			case fred().xyzabc: System.out.println();
		}
	}
	MyObj fred() {
		return new MyObj(0);
	}
}

record MyObj(int myProp) {
	public static final int xyzabc = 0;
}
```

This is because you are not allowed to invoke `fred()` in the case statement.

and the test case seems to be about converting `case fred().xyz` to `case fred().xyzabc`

**Comment by datho7561** [comment]
@srikanth-sankaran @jarthana This PR is ready for review. The tests are passing.

**Comment by srikanth-sankaran** [comment]
I'll take a look in a couple of days. Thanks

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran @jarthana This PR is ready for review. The tests are passing.
> 
> I still have to add code generation, but in order to test code generation, I will need #1517, since you need to use unnamed variables in order to use lists of Patterns in case statements.

In that case, let us focus and prioritize #1517 please. That PR needs to be rebased and updated and then I will help close it.

**Comment by srikanth-sankaran** [comment]
@datho7561 - I have made us joint owners of this. I would like to include this as part of the comprehensive cleaup to pattern code generation rather than rush through this.

**Comment by jukzi** [comment]
that "4 new warnings" seem unrelated and should go away when you rebase on master
https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-1742/16/eclipse/new/
image

**Comment by datho7561** [comment]
I've been working on rebasing this PR. It seems many things are working properly. However, I've hit a roadblock when it comes to fallthrough with cases with pattern. I've figured out some hacks to get this working:

```java
public class Issue712_001 {
	public static void main(String[] args) {
		Object o = "Hello World";
		foo(o);
	}

	public static void foo(Object o) {
		switch (o) {
		case String s:
			System.out.println(s); // No break!
		case R():
			System.out.println("It's either an R or a string"); // Allowed
			break;
		default:
		}
	}
}

record R() {}
record S() {}
```

However, then I ran into a `javac` bug (I've hopefully submitted this properly upstream). I have no idea what's supposed to happen in this case:

```java

public class fallthroughPattern {

	public static void main(String... args) {
		Object o = "";
		switch (o) {
		case String s:
			System.out.println("this is the first outcome");
		case R(String _):
			System.out.println("this is the second outcome");
		case R(Integer _):
			System.out.println("this is the third outcome");
		default:
			System.out.println("this is the fourth outcome");
		}

	}

	private static final record R<T>(T a) {}

}
```

**Comment by srikanth-sankaran** [comment]
Thanks David. Note that Jay reported three problems of which fixes for only two are pushed to that PR. I am working on the other one which very likely is involved in the case you cite. 

I expect to push a fix before end of business Wednesday. 

Do you have a link for the javac defect you reported ??

**Comment by srikanth-sankaran** [comment]
Please pick up the latest from the cumulative pattern fixes PR. I fixed a few problems today. May be it will be of help in what issues you are facing

**Comment by datho7561** [comment]
> I am working on the other one which very likely is involved in the case you cite.

Thank you!

> Do you have a link for the javac defect you reported ??

I tried opening the bug right after I reported it, but I couldn't find it. I'll try again

> I fixed a few problems today. May be it will be of help in what issues you are facing

I'll rebase against your PR today. I might as well push the somewhat working rebase as well.

**Comment by datho7561** [comment]
I still wasn't able to find the bug I submitted to javac regarding switch statements with patterns with fallthrough. Maybe I'll try submitting again?

I think that I got all the tests working after rebasing on your latest change, just running locally to ensure nothing bad happened.

**Comment by srikanth-sankaran** [comment]
> I still wasn't able to find the bug I submitted to javac regarding switch statements with patterns with fallthrough. Maybe I'll try submitting again?


Could you describe here what the defect is ? Sometimes there is a latency as I recall. 


> I think that I got all the tests working after rebasing on your latest change, just running locally to ensure nothing bad happened.

Excellent. I'll look into absorbing it into the cumulative fixes branch this week. Any case I would like to wrap up this work by end of Feb.

**Comment by srikanth-sankaran** [comment]
Not being an expert in git/github, I wonder how I would see just the diffs wrt to https://github.com/srikanth-sankaran/eclipse.jdt.core/tree/patterns-accumulated-fixes branch head.

Let me know if you think this is ready for me to start with the review and absorbing the changes

**Comment by srikanth-sankaran** [comment]
> Not being an expert in git/github, I wonder how I would see just the diffs wrt to https://github.com/srikanth-sankaran/eclipse.jdt.core/tree/patterns-accumulated-fixes branch head.
> 
> Let me know if you think this is ready for me to start with the review and absorbing the changes

Ignore the above. I have started reviewing the changes and will move them to https://github.com/srikanth-sankaran/eclipse.jdt.core/tree/patterns-accumulated-fixes in logical chunks.

**Comment by srikanth-sankaran** [comment]
I have picked up the changes from here and pushed them to https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2011 - action can continue there. I am reviewing the changes and will push additional commits for any issues I find during review/testing. I may ask for help with some tasks - any additional commits can be against the srikanth-sankaran:patterns-accumulated-fixes branch

**Pull request closed without merging**
