### PR TITLE
Suboptimal/No code completion suggestions for switching on sealed interfaces

### PR DESCRIPTION
**Pull request by srikanth-sankaran**
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3300

### CODE REVIEW

**Comment by srikanth-sankaran** [comment]
@jarthana - this passes RunModelTests

Fix is simple. Remove the wrong gate at JDK17 and replace it with JDK21 where enhanced switches became available.
Also a bunch of tests had to be moved from wrong home to right home and expectations adjusted

This can give a usability boost and so should be included for 4.34

CI appears stalled - simply says queued and doesn't run the tests

**Review by jarthana — APPROVED** [review]

**Comment by srikanth-sankaran** [comment]
Thanks for the review and approval @jarthana  - in the absence of this fix, the scenario in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3300 is completely broken!!

**Comment by jarthana** [comment]
+1 for RC1. Let's wait for the tests to run.

**Comment by jarthana** [comment]
@MohananRahul  are there any more builds for RC1?

**Comment by jarthana** [comment]
I had an offline discussion with Rahul who confirmed we have two more builds for RC1.
@srikanth-sankaran yes, please proceed with merging the PR.

**Comment by srikanth-sankaran** [comment]
Thanks Jay!

**Comment by stephan-herrmann** [comment]
> Also a bunch of tests had to be moved from wrong home to right home and expectations adjusted

@srikanth-sankaran  Was that a one time correction, i.e., have tests been placed in the wrong class initially, or is our strategy where to place tests suboptimal? For features with several preview versions I don't think we want to routinely move tests from one test class to another (for the sake of history of course).

**Comment by srikanth-sankaran** [comment]
> > Also a bunch of tests had to be moved from wrong home to right home and expectations adjusted
> 
> @srikanth-sankaran Was that a one time correction, i.e., have tests been placed in the wrong class initially, or is our strategy where to place tests suboptimal? For features with several preview versions I don't think we want to routinely move tests from one test class to another (for the sake of history of course).

Here is the picture before the fix:

* Completion suggestions were offered for switching on Objects at compliance 17. They should not be.
* Completion suggestions were NOT offered for switching on Objects at compliance 21. They should be.
* Test was placed in compliance level 17 suite.

Once I corrected the first two, the old tests in 17 suite started failing and had to be moved to the new home.

**Pull request merged**
