### PR TITLE
[23][Primitive Patterns][Preview] VerifyError during conversion between T extends Long and double #3181

### PR DESCRIPTION
**Pull request by stephan-herrmann**
+ attempt to compensate for jumps with different start stack depth

Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3181

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
@srikanth-sankaran this is the smaller of two fixes I could think of, but I'm neither sure if it's complete, nor if it is good design:

I'm a bit uneasy about the asymmetry between these existing two branches in `RecordPattern.generateCode()`:
```java
	if (p instanceof TypePattern) {
		((TypePattern) p).generateTypeCheck(currentScope, codeStream, innerFailLabel);
	} else {
		codeStream.instance_of(p.resolvedType); // lastComponent ? named ? ([C, boolean] : [R, C, boolean]) : ([boolean] : [R, boolean])
	}
```

While `instance_of` only converts a object value into 0 or 1, as the input to subsequent `ifne` (the positive branch), inside `generateTypeCheck()` different things can happen, one of them being:
```java
				codeStream.ifnull(falseLabel);
				codeStream.iconst_1();
```
i.e., in one case we already *perform* the jump *for the negative case*. This caused different jumps to the same label from locations with different stackDepth!

Would it be cleaner if `generateTypeCheck()` would refrain from any jumping, and only signal some "code" indicating which instruction should be used for type checking (if any)? Unfortunately, the JVM has no bytecode for comparison against `null` *without* jumping (i.e., some `a != null ? 1 : 0` idiom).

Alternatively, we could just flip the jumps to target innerTruthLabel, rather than matchFailLabel/innerFailLabel.

Things are a bit more involved since `InstanceOfExpression.generateOptimizedBoolean()` uses `generateTypeCheck()` *always* and then has several downstream branches with different jump-strategies.

**Comment by srikanth-sankaran** [comment]
> Unfortunately, the JVM has no bytecode for comparison against `null` _without_ jumping (i.e., some `a != null ? 1 : 0` idiom).

Sure, it does! 😆 

This patch fixes the present problem but I need to see if it gels well with `org.eclipse.jdt.internal.compiler.ast.InstanceOfExpression.generateOptimizedBoolean(BlockScope, CodeStream, BranchLabel, BranchLabel, boolean)`'s usage of `generateTypeCheck`

```
diff --git a/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/IGenerateTypeCheck.java b/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/IGenerateTypeCheck.java
index 5565d8a..b9819b5 100644
--- a/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/IGenerateTypeCheck.java
+++ b/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/IGenerateTypeCheck.java
@@ -46,8 +46,7 @@
 			}
 			case WIDENING_REFERENCE_AND_UNBOXING_COVERSION,
 			WIDENING_REFERENCE_AND_UNBOXING_COVERSION_AND_WIDENING_PRIMITIVE_CONVERSION -> {
-				codeStream.ifnull(falseLabel);
-				codeStream.iconst_1();
+				codeStream.instance_of(scope.getJavaLangObject());
 				setPatternIsTotalType();
 			}
 			case NARROWING_AND_UNBOXING_CONVERSION -> {
@@ -56,8 +55,7 @@
 			}
 			case UNBOXING_CONVERSION,
 			UNBOXING_AND_WIDENING_PRIMITIVE_CONVERSION -> {
-				codeStream.ifnull(falseLabel);
-				codeStream.iconst_1();
+				codeStream.instance_of(scope.getJavaLangObject());
 				setPatternIsTotalType();
 			}
 			case NO_CONVERSION_ROUTE -> {

```

**Comment by srikanth-sankaran** [comment]
> Would it be cleaner if `generateTypeCheck()` would refrain from any jumping

I much prefer that as it gives the caller flexibility over what to do.

**Comment by srikanth-sankaran** [comment]
The patch passes RVPT - ergo it doesn't irritate InstanceOfExpression.generateOptimizedBoolean - I didn't white box validate that. 

So if this is the final solution, you can start a tally. Seeing that you are getting beverages from others 😆

**Comment by srikanth-sankaran** [comment]
You can use the comments of the form `// lastComponent ? named ? ([C, boolean] : [R, C, boolean]) : ([boolean] : [R, boolean])` in `org.eclipse.jdt.internal.compiler.ast.RecordPattern.generateCode(BlockScope, CodeStream, BranchLabel, BranchLabel)` to keep track of operand stack and ensure that every path to a bci matches up every other path. So statically we can be sure there is no shape violation

**Comment by stephan-herrmann** [comment]
> > Unfortunately, the JVM has no bytecode for comparison against `null` _without_ jumping (i.e., some `a != null ? 1 : 0` idiom).
> 
> Sure, it does! 😆

I said "without jumping", so show me the byte code!

**Comment by stephan-herrmann** [comment]
@srikanth-sankaran  feel free to grab this one.

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran feel free to grab this one.

Ok, I will take this forward and help wrap up both https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3129 and https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3181

**Comment by srikanth-sankaran** [comment]
I tried pushing to here, but due to some glitch in my secure store setup I wasn't. So I have created a fresh PR: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3307

Given where we are, it may require two reviews. I'll raise a request there

**Pull request closed without merging**
