### PR TITLE
Prevent duplicate constructor completion proposals

### LINKED ISSUE #195: [content assist] Duplicate constructor completion
Version: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/ba0944dbadfa1fbfd5927e80084ffe03718c43d4

Steps to reproduce:
constructor

A related issue -https://github.com/eclipse/eclipse.jdt.ls/issues/2147

### PR DESCRIPTION
**Pull request by snjeza**
Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

## What it does
Fixes #195 

## Author checklist

- I have thoroughly tested my changes
- The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by snjeza** [comment]
test this please

**Review by rgrunber — COMMENTED** [review]
When `qualifiedBinding` is just a `PackageBinding` then that could be the case of a constructor completion, so `findTypesAndSubpackages(..)` (from above it) seems to find the necessary constructors so no need to do it once again. The change makes sense.

@snjeza can you change the commit message title to something like :
`Prevent duplicate constructor completion proposals`

**Comment by snjeza** [comment]
> can you change the commit message title to something like :
Prevent duplicate constructor completion proposals

@rgrunber I have changed it.

**Comment by rgrunber** [comment]
Any idea why it's failing now ?

**Review by rgrunber — APPROVED** [review]
The failure is a known issue it seems, relating to Tycho. Given that the tests passed before, and the only new change was the commit message, I think this should be fine to merge.

See https://github.com/eclipse/tycho/issues/1124

**Pull request merged**
