### PR TITLE
[23] JEP 482: Flexible Constructor Bodies (Second Preview)

### PR DESCRIPTION
**Pull request by stephan-herrmann**
Preparation
+ renamed the feature from "Statements before Super" to "Flexible Constructor Bodies"
+ move the main flag to let ClassScope manage early construction contexts

Implement updates for JEP 482:
+ change wording towards "early construction context"
+ determine early-ctor-ctx based on target class
  fine tuning:
  - where should enclosing types be considered?
  - search for enclosings first but also consider their supers in a second round
+ reduce # mechanisms for detecting early construction context
+ allow assignment to fields of uninitialized instance
+ differentiate new errors: 
   - FieldReadInEarlyConstructionContext
   - ThisInEarlyConstructionContext
   - AllocationInEarlyConstructionContext
   - MessageSendInEarlyConstructionContext
   - DuplicateExplicitConstructorCall
   - ConstructorCallNotAllowedHere
   - SuperFieldAssignInEarlyConstructionContext
   - AssignFieldWithInitializerInEarlyConstructionContext
+ fine tune generation of synthetic arguments and fields for enclosing instances
   - such synthetics allow to skip over unavailable enclosing instances towards outer instances that are available

Documentation of key strategies as javadoc / code comments:
+ enablement: `JavaFeature.FLEXIBLE_CONSTRUCTOR_BODIES`
  - this is relevant because effects of this feature spread wide into the code, explains which invariants still help to keep the number of checks low
+ detection / analysis: `ClassScope.insideEarlyConstructionContext`
   - describes the combination of structural and temporary contexts
+ explicit vs implicit constructor calls: `ConstructorDeclaration.resolveStatements()`
   - code comment describing updated contract of `ConstructorDeclaration.constructorCall`
+ code gen: `TypeDeclaration.manageEnclosingInstanceAccessIfNecessary(BlockScope, FlowInfo)`
   - code comments describing the strategy to generate synth args & fields for various outer classes, which orchestrates code generation

Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2472

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
```
[2024-07-08T23:03:05.130Z] Recording test results
[2024-07-08T23:03:10.178Z] Remote call on JNLP4-connect connection from 10.40.67.109/10.40.67.109:55204 failed
Error when executing always post condition:
java.lang.OutOfMemoryError: Java heap space
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: d7a4272b-c950-4119-abdb-cb7626762b8f
Caused: java.io.IOException: Remote call on JNLP4-connect connection from 10.40.67.109/10.40.67.109:55204 failed
	at hudson.remoting.Channel.call(Channel.java:1007)
	at hudson.FilePath.act(FilePath.java:1226)
	at hudson.FilePath.act(FilePath.java:1215)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:125)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:160)
	at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:254)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:857)
```

hmm?

**Comment by stephan-herrmann** [comment]
> ```
> [2024-07-08T23:03:05.130Z] Recording test results
> java.lang.OutOfMemoryError: Java heap space
> ```

Actually jenkins was trying to tell me that the logs were just to big, due to too many errors actually, ups.

**Comment by stephan-herrmann** [comment]
The next big step will be accessing outers in complex nesting situations, where enclosing-instance fields (`this$0` ...) may not yet be available.

For one particular case, I received clarification on [amber-spec-experts](https://mail.openjdk.org/pipermail/amber-spec-experts/2024-July/004182.html), resulting in https://bugs.openjdk.org/browse/JDK-8336255 (javac wrongly signals an error).

**Comment by stephan-herrmann** [comment]
Jenkins keeps reporting this as [a "new" issue](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2685/6/eclipse/new/):
```SourceRange implements non-API interface ISourceRange```

Neither SourceRange nor ISourceRange has been changed "recently". How is that a **new issues**?

And when ISourceRange says: `@noimplement This interface is not intended to be implemented by clients.` why should this affect class SourceRange which is not a "client", it sits right next to the interface.

Even the fact that this build is compared against `eclipse.jdt.core-github/master` build doesn't explain any of this.

I can see the same problem on at least one other PR for BETA_JAVA23: https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/view/change-requests/job/PR-2687/1/eclipse/

@iloveeclipse any idea what's going on?

**Comment by stephan-herrmann** [comment]
> Neither SourceRange nor ISourceRange has been changed "recently". How is that a **new issues**?

Found it, commit https://github.com/eclipse-jdt/eclipse.jdt.core/commit/656af06f "stole" one relevant API filter during conflict resolution. @jarthana I don't see a reference to any PR, did jenkins ever test that commit?

**Comment by stephan-herrmann** [comment]
@srikanth-sankaran this PR is on it's home stretch.

Should you like to review it before merging into BETA_JAVA23 please let me know.

You'll note that the change cuts both wide and deep, so you may want to familiarize yourself with the matter sooner or later, but do so at _your_ pace.

Also I'm ready to take up as many post-merge follow-up issues as it needs, it's beta anyway :)

**Comment by stephan-herrmann** [comment]
Two more requests for clarification / spec update:
* https://mail.openjdk.org/pipermail/amber-spec-experts/2024-July/004185.html
* https://mail.openjdk.org/pipermail/amber-spec-experts/2024-July/004186.html
  * this thread contains an answer to the former

We essentially know what's intended, but obviously it would be great to see the same also in the specification.

**Comment by stephan-herrmann** [comment]
There's also a collection of related javac bugs
* https://bugs.openjdk.org/browse/JDK-8334248?jql=labels%20%3D%20javac-pre-capture%20ORDER%20BY%20status%20ASC

Obviously, any exceptions in javac are not very interesting for us, but I might get a few interesting tests there and from previous discussions on mailing lists...

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran this PR is on it's home stretch.
> 
> Should you like to review it before merging into BETA_JAVA23 please let me know.

I don't expect to have the time to review now, but thanks for the alert - I will schedule it later and familiarize myself with them,

**Pull request merged**
