### PR TITLE
Avoid read source twice during compile #2691

### PR DESCRIPTION
**Pull request by jukzi**
Use parse() instead of dietParse() to avoid parse during Parser.getMethodBodies()

https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2691

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Should this be a draft too (like https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2695/)? I assume you are experimenting with the right solution?

**Comment by jukzi** [comment]
i do not understand why the build fails before executing tests.because jdt compiles itself? how to get test results ?

**Comment by iloveeclipse** [comment]
> i do not understand why the build fails before executing tests.because jdt compiles itself? how to get test results ?

If JDT can't compile itself it is already a test failure :-)

**Comment by iloveeclipse** [comment]
The background is: we first compile batch compiler from sources using old compiler and then continue with compilation of the code with the freshly built compiler. This is another way to test real code not just some test snippets.

**Comment by iloveeclipse** [comment]
So basically it says that compiler is unable to build JDT anymore with your changes.

**Comment by jukzi** [comment]
yea, can i disable that to get a little bit more detail why it fails to compile?

**Comment by iloveeclipse** [comment]
You could try to temporarily disable that in Jenkins file, but may be you can try to compile same code in the IDE in debugger first either from Main or IDE from IDE (not sure if that would be specific to batch compiler invocation)?

**Comment by jukzi** [comment]
i compiled the whole platform workspace first locally in the ide- successully  :-/

**Comment by iloveeclipse** [comment]
So you can try to run org.eclipse.jdt.internal.compiler.batch.Main directly from debugger with the source in question.

**Comment by jukzi** [comment]
@stephan-herrmann in principle this change looks harmeless simple but it causes Problem markers when imports are only used in javadoc:
image
Can you help to solve that riddle? I guess its a problem that could and should be solved independently of this PR.

**Pull request closed without merging**
