### PR TITLE
JavaSearchScope: improve encloses() performance  #474

### PR DESCRIPTION
**Pull request by jukzi**
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/496#issuecomment-1788512275

### CODE REVIEW

**Comment by jukzi** [comment]
build failed with org.eclipse.tycho:tycho-maven-plugin:4.0.0-SNAPSHOT not found. @akurtakov @laeubi ?
```
6:01:29  [WARNING] The POM for org.eclipse.tycho:tycho-maven-plugin:jar:4.0.0-SNAPSHOT is missing, no dependency information available
16:01:29  [ERROR] [ERROR] Some problems were encountered while processing the POMs:
16:01:29  [ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:4.0.0-SNAPSHOT or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.eclipse.tycho:tycho-maven-plugin:jar:4.0.0-SNAPSHOT (absent): Could not find artifact org.eclipse.tycho:tycho-maven-plugin:jar:4.0.0-SNAPSHOT in tycho-snapshots (https://repo.eclipse.org/content/repositories/tycho-snapshots/) @ 

```

**Comment by laeubi** [comment]
@jukzi current Tycho snapshot is `4.0.4-SNAPSHOT` or released `4.0.0` -- `4.0.3` see
- https://github.com/eclipse-tycho/tycho/discussions/2455

**Comment by jukzi** [comment]
> @jukzi current Tycho snapshot is `4.0.4-SNAPSHOT` or released `4.0.0` -- `4.0.3` see

what am i supposed todo with that information?

**Comment by jukzi** [comment]
rebased. hope that helps

**Comment by jukzi** [comment]
@eric-milles WDYT?

**Comment by gayanper** [comment]
@jukzi how does this help to improve performance, I only see getting rid of a loop and replacing it with Set.contains ? Am I missing something important here ?

**Comment by jukzi** [comment]
> @jukzi how does this help to improve performance, I only see getting rid of a loop and replacing it with Set.contains

exactly. When n is the number of elements the loop has O(n) runtime while "contains" takes O(1) for a hashSet.

**Comment by jukzi** [comment]
@eric-milles can you please measure if this variant solves your problem?

**Comment by gayanper** [comment]
> > @jukzi how does this help to improve performance, I only see getting rid of a loop and replacing it with Set.contains
> 
> 
> 
> exactly. When n is the number of elements the loop has O(n) runtime while "contains" takes O(1) for a hashSet. 

Sorry i missed the HashSet part. I hope all the IJavaElement we handle here implements hashCode and equals.

**Pull request merged**
