### PR TITLE
Remove generated jdtCompilerAdapter.jar from sources

### PR DESCRIPTION
**Pull request by iloveeclipse**
jdtCompilerAdapter.jar is generated by maven on build, why it is inside source tree ???

### CODE REVIEW

**Comment by iloveeclipse** [comment]
As we see (tests are green), the jar is not needed for maven build & tests, because it is generated & packaged into the jdt.core jar (!) anyway.
I believe the only reason to have this jar is the code in org.eclipse.ant.internal.ui.datatransfer.BuildFileCreator that, if running Eclipse from Eclipse, will fail to find & link the jar.

@SarikaSinha , @vik-chand : is my assumption correct and the jar **in the source tree** is only needed for debugging in the IDE?
If so, I would propose to fix BuildFileCreator & remove this jar from sources.

**Comment by iloveeclipse** [comment]
OK, another really weird reason is [this one](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/592#issuecomment-1339681717): bundles that use this jar at **compile time** because it can be ["added" to PDE classpath](https://github.com/groovy/groovy-eclipse/blob/bacc5e539a6461e9a3c44ad17886adab97cca847/ide/org.codehaus.groovy.eclipse.ant/build.properties#L14) via 

`jars.extra.classpath=platform:/plugin/org.eclipse.jdt.core/jdtCompilerAdapter.jar`

Not sure if that would work if jdt bundle is in the workspace **without** the jar.

Ideally in both cases that should be taken not from the jar that is checked into the source tree but from jar that is in the platform.

**Comment by iloveeclipse** [comment]
I think most practical solution would be to remove the jar from git and instead create this jar with external builder on every change from batch compiler code or by copying from the platform.

**Comment by eric-milles** [comment]
`org.codehaus.groovy.eclipse.ant` depends on `platform:/plugin/org.eclipse.jdt.core/jdtCompilerAdapter.jar` (for `JDTCompilerAdapter`) much like `org.eclipse.jdt.core` depends on `platform:/plugin/org.apache.ant/lib/ant.jar` for basic Ant types.

In fact, noticing this, I was able to reduce my bundle dependencies by replacing `Require-Bundle: org.apache.ant,org.eclipse.jdt.core` (in MANIFEST.MF) with `jars.extra.classpath=platform:/plugin/org.apache.ant/lib/ant.jar,platform:/plugin/org.eclipse.jdt.core/jdtCompilerAdapter.jar` (in build.properties).

At this moment, both `org.eclipse.jdt.core` and `org.codehaus.groovy.eclipse.ant` projects do not create `jdtCompilerAdapter.jar` and `groovyAntEclipse.jar` respectively when built within PDE.  When launching Eclipse IDE from PDE, the Ant extensions are not present if these jars do not exist.  I think this is a reason JDT Core carries this jar in git.  But, as you describe it could be generated and this gap would be closed.

**Pull request closed without merging**
