### PR TITLE
Fix the meta index values for type declarations #533

### PR DESCRIPTION
**Pull request by gayanper**
## What it does
The type declaration qualifiers are added with a '$' which cause index misses. Since the indexes needs to be rebuilt after applying the fix, the disk index signature is updated.

## How to test
- Integration tests
- Test with #532

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by gayanper** [comment]
@iloveeclipse please have a look, most importantly about the disk index signature bump to rebuild all indexes.

**Comment by iloveeclipse** [comment]
Sorry Gayan, I'm as usually totally under water with other tasks, so can't guarantee anything here.

**Comment by gayanper** [comment]
I would like to merge this soon so that index regeneration problems can be found early in the release cycle. @iloveeclipse @stephan-herrmann let me know if you see otherwise.

**Comment by iloveeclipse** [comment]
Sure. Earlier is better.

**Comment by gayanper** [comment]
Fixes #533

**Comment by testforstephen** [comment]
@gayanper A small suggestion for PR merge, It might be better to use "**Squash and merge**" to keep the git history clean.

**Comment by gayanper** [comment]
> @gayanper A small suggestion for PR merge, It might be better to use "**Squash and merge**" to keep the git history clean.

My bad 😕, thanks for pointing out @testforstephen. I missed to rebase before the merge. I should default to squash merge to be safe in future. 

May be we should look into configuring squashing as default merge strategy. Cannot remember if we had that discussion when moving to github. But will start a discussion for that.

**Comment by testforstephen** [comment]
> May be we should look into configuring squashing as default merge strategy. Cannot remember if we had that discussion when moving to github. But will start a discussion for that.

Agree, to ensure a linear history, we should only turn on squashing or rebasing merge for PR in GitHub repo settings.

image

**Pull request merged**
