### PR TITLE
ArrayIndexOutOfBoundsException during Java Search.Fixes #488

### LINKED ISSUE #488: ArrayIndexOutOfBoundsException during Java Search
revision: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/528dc7e08311c59735d33154cf7e532758b55bd8
Steps to reproduce:

- import https://github.com/redhat-developer/vscode-java/files/9708915/test.zip
- open PartBuilder.java
- right click acceptLine in line 22, select References>Workspace

You will get the following exception:

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getOrCreateDeclaredPackage(ModuleBinding.java:338)
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule.getDeclaredPackage(ModuleBinding.java:104)
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.combineWithPackagesFromOtherRelevantModules(ModuleBinding.java:669)
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getVisiblePackage(ModuleBinding.java:614)
	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding.getTopLevelPackage(ModuleBinding.java:551)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTopLevelPackage(LookupEnvironment.java:1686)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3557)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3187)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:60)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:522)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:625)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveTypeArgument(TypeReference.java:638)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.internalResolveLeafType(ParameterizedSingleTypeReference.java:264)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.internalResolveType(ParameterizedSingleTypeReference.java:174)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.resolveType(ParameterizedSingleTypeReference.java:390)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:621)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveTypeForQualifiedAllocationExpression(QualifiedAllocationExpression.java:377)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.resolveType(QualifiedAllocationExpression.java:304)
	at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.resolve(FieldDeclaration.java:294)
```

A potential path:
```
diff --git a/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/lookup/ModuleBinding.java b/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/lookup/ModuleBinding.java
index f30e61acd4..432ec2b6e9 100644
--- a/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/lookup/ModuleBinding.java
+++ b/org.eclipse.jdt.core/compiler/org/eclipse/jdt/internal/compiler/lookup/ModuleBinding.java
@@ -96,7 +96,7 @@ public class ModuleBinding extends Binding implements IUpdatableModule {
                @Override
                PlainPackageBinding getDeclaredPackage(char[] flatName) {
                        PlainPackageBinding declaredPackage = super.getDeclaredPackage(flatName);
-                       if (declaredPackage == null && this.environment.useModuleSystem) {
+                       if (declaredPackage == null && flatName.length > 0 && this.environment.useModuleSystem) {
                                IModuleAwareNameEnvironment moduleEnv = (IModuleAwareNameEnvironment) this.environment.nameEnvironment;
                                char[][] compoundName = CharOperation.splitOn('.', flatName);
                                char[][] declaringModuleNames = moduleEnv.getUniqueModulesDeclaringPackage(compoundName, nameForLookup());
```

A related issue: https://github.com/redhat-developer/vscode-java/issues/2710

### PR DESCRIPTION
**Pull request by snjeza**
Steps to reproduce:

- import https://github.com/redhat-developer/vscode-java/files/9708915/test.zip
- open PartBuilder.java
- right click acceptLine in line 22, select References>Workspace

### CODE REVIEW

**Comment by gayanper** [comment]
@snjeza is there a possibility to add a test for this ? We can keep the source and compiled binaries for testing. For example if you need binary classes for the tests, you can add those classfiles into test project source and also keep the source files of those binary files incase we want to compile them or have look at them again incase.

**Comment by snjeza** [comment]
@gayanper Working on that.

**Comment by snjeza** [comment]
@gayanper Could you, please, review #828? It fixes the issue and includes a test.

**Comment by gayanper** [comment]
> @gayanper Could you, please, review #828? It fixes the issue and includes a test.

Should we then close this ?

**Comment by snjeza** [comment]
> Should we then close this ?

Agree.

**Pull request closed without merging**
