### PR TITLE
Added ASTRewrite support(Unit test & Rewrite) and ASTConverter unit test

### PR DESCRIPTION
**Pull request by subyssurendran666**
## What it does
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2294

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by mpalat** [comment]
@subyssurendran666 can you rechek whether you have baselined? I see 61 files changed!

**Comment by stephan-herrmann** [comment]
> @subyssurendran666 can you rechek whether you have baselined? I see 61 files changed!

@mpalat This could be the consequence of bad merge #2888 in which case it will be difficult to separate wanted from unwanted changes. Let's suspend this PR until #2892 is merged.

**Comment by subyssurendran666** [comment]
@mpalat @stephan-herrmann I suspect that instead of rebasing, I accidentally merged with the BETA_JAVA23 branch. Therefore I'll create a new PR for the feature.

**Comment by stephan-herrmann** [comment]
> @mpalat @stephan-herrmann I suspect that instead of rebasing, I accidentally merged with the BETA_JAVA23 branch. Therefore I'll create a new PR for the feature.

You may still want to wait until we're on safe ground again, i.e., after #2892 has been merged.

**Comment by stephan-herrmann** [comment]
@subyssurendran666 I see a flood of PRs being closed with the notice "@[subyssurendran666](https://github.com/subyssurendran666) closed this by deleting the head repository"

Was that another accident?

**Comment by subyssurendran666** [comment]
> @subyssurendran666 I see a flood of PRs being closed with the notice "@[subyssurendran666](https://github.com/subyssurendran666) closed this by deleting the head repository"
> 
> Was that another accident?

Deleting the fork was intentional due to an issue in the BETA_JAVA23 branch of my fork that I couldn't resolve. At the time, deleting the fork seemed like the best option.

**Pull request closed without merging**
