### PR TITLE
switch statement with yield and try/catch produces EmptyStackException

### LINKED ISSUE #1394: switch statement with yield and try/catch produces EmptyStackException
We wanted to upgrade to STS 4.20.0, which is based on Eclipse Platform 4.29.0 and includes Eclipse Java Development Tools 3.19.200. Unfortunately, after the update, we are running into the following error:
```
java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:103)
	at java.base/java.util.Stack.pop(Stack.java:85)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.popTypeBinding(CodeStream.java:7803)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.ireturn(CodeStream.java:5645)
	at org.eclipse.jdt.internal.compiler.codegen.StackMapFrameCodeStream.ireturn(StackMapFrameCodeStream.java:449)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.generateReturnBytecode(CodeStream.java:2593)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.generateReturnBytecode(ReturnStatement.java:257)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.generateCode(ReturnStatement.java:240)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:355)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:292)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:763)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:833)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:413)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1324)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:790)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1245)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:868)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider$1.run(CoreASTProvider.java:294)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.createAST(CoreASTProvider.java:286)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:199)
	at org.eclipse.jdt.core.manipulation.SharedASTProviderCore.getAST(SharedASTProviderCore.java:138)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:166)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$1.run(SelectionListenerWithASTManager.java:151)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
```
eclipse.buildId=4.20.0.202309081654
java.version=20.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.springframework.boot.ide.branding.sts4 -product org.springframework.boot.ide.branding.sts4
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springframework.boot.ide.branding.sts4 -data file:/D:/work/workspaces/sts4/sts-test/ -product org.springframework.boot.ide.branding.sts4
```

I tracked it down to an issue with a switch statement, a labeled expression, yield and try/catch. Similar to the following code example, which triggers the EmptyStackException as well:
```java
	private static int switchWithYield() {
		String myStringNumber = "1";
		return switch (myStringNumber) {
		case "1" -> {
			try {
				yield Integer.parseInt(myStringNumber);
			} catch (NumberFormatException e) {
				throw new RuntimeException("Failed parsing number", e);
			}
		}
		default -> throw new IllegalArgumentException("Unexpected value: " + myStringNumber);
		};
	}
``` 
Compiler compliance level is 17.

The same code perfectly compiles with STS 4.19.0 based on Eclipse Platform 4.28.0 and and included Eclipse Java Development Tools 3.19.100.

### PR DESCRIPTION
**Pull request by jarthana**
#1394

## What it does
Fixes #1394

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by srikanth-sankaran** [comment]
@jarthana if you roll up all the offending snippets into regression tests and let me know it is ready for review, I am happy to review. Thanks

**Comment by jarthana** [comment]
> @jarthana if you roll up all the offending snippets into regression tests and let me know it is ready for review, I am happy to review. Thanks

I am not confident enough about the patch. This is more of an experiment. @mpalat is probably the better person to take this forward.
And I am off most of December to be able to look into this for M1.

**Comment by srikanth-sankaran** [comment]
Ok, I'll work on this for M1 and will pull in Manoj as needed.

**Comment by srikanth-sankaran** [comment]
No, this is a wrong fix. I'll propose a PR and take it forward.

**Pull request closed without merging**
