### PR TITLE
ECJ fails: Problem detected during type inference: Unknown error at invocation of getReadOnly(P)

### PR DESCRIPTION
**Pull request by stephan-herrmann**
tentative fix for #2413

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@laeubi : there are three errors reported at the end of the build, which I believe tycho related:

```
01:34:29  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8-SNAPSHOT:validate-classpath (default-validate-classpath) on project org.eclipse.jdt.apt.ui: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8-SNAPSHOT:validate-classpath failed: bundleLocation can't be null for artifact eclipse-plugin:org.eclipse.compare:3.11.0.v20240516-1116: null -> [Help 1]
01:34:29  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8-SNAPSHOT:validate-classpath (default-validate-classpath) on project org.eclipse.jdt.apt.pluggable.tests: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8-SNAPSHOT:validate-classpath failed: bundleLocation can't be null for artifact eclipse-plugin:org.eclipse.compare:3.11.0.v20240516-1116: null -> [Help 1]
01:34:29  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8-SNAPSHOT:validate-classpath (default-validate-classpath) on project org.eclipse.jdt.apt.tests: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8-SNAPSHOT:validate-classpath failed: bundleLocation can't be null for artifact eclipse-plugin:org.eclipse.compare:3.11.0.v20240516-1116: null -> [Help 1]
```
Could you please take a look?

**Comment by laeubi** [comment]
Maybe PR needs a rebase?

**Comment by iloveeclipse** [comment]
> I've re-triggered the build just in case something was wrong with internet.

Yes, internet was broken. The one failing test now is known to be unstable.

**Comment by stephan-herrmann** [comment]
> > I've re-triggered the build just in case something was wrong with internet.
> 
> Yes, internet was broken. The one failing test now is known to be unstable.

Thanks.

FYI, I'm not planning to merge this for 4.32, I don't feel that the fix is safe for RC1.

**Comment by stephan-herrmann** [comment]
likely superseded by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2488 - let's see.

**Comment by stephan-herrmann** [comment]
> likely superseded by #2488 - let's see.

Indeed so, closing this one.

**Pull request closed without merging**
