### PR TITLE
Run the JavaCoreStandaloneTest in the build

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1720

### CODE REVIEW

**Comment by merks** [comment]
@laeubi 

It looks like the test didn't run.
```
14:47:44  [INFO] --- surefire:3.2.2:test (test-standalone) @ org.eclipse.jdt.core.tests.model ---
14:47:50  [INFO] Toolchain in maven-surefire-plugin: JDK[/opt/tools/java/openjdk/jdk-21/latest]
14:47:50  [INFO] No tests to run.
14:47:50  [INFO] 
```
Did I miss something or do do anything obviously wrong?

The test does exist:

image

**Comment by laeubi** [comment]
If it is really a maven surefire test (only) you might want to look at:

- https://tycho.eclipseprojects.io/doc/latest/TestingBundles.html#maven-surefire-plugin
- https://github.com/eclipse-tycho/tycho/tree/master/demo/testing/surefire/with-source-folder

but this is a "traditional" `eclipse-plugin-test` layout you probably need to instruct surefire with

https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#testClassesDirectory

to look at the default output directory (in contrast to the test output director) e.g. `<testClassesDirectory>${project.build.outputDirectory}</testClassesDirectory>` to find the test-classes.

**Comment by merks** [comment]
I can see this in the log:
```
16:34:46  [INFO] --- surefire:3.2.2:test (test-standalone) @ org.eclipse.jdt.core.tests.model ---
16:34:50  [INFO] Toolchain in maven-surefire-plugin: JDK[/opt/tools/java/openjdk/jdk-21/latest]
16:34:50  [INFO] Using configured provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
16:34:50  [INFO] 
16:34:50  [INFO] -------------------------------------------------------
16:34:50  [INFO]  T E S T S
16:34:50  [INFO] -------------------------------------------------------
16:34:51  [INFO] Running org.eclipse.jdt.core.tests.model.JavaCoreStandaloneTest
16:34:51  [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.174 s -- in org.eclipse.jdt.core.tests.model.JavaCoreStandaloneTest
16:34:51  [INFO] 
16:34:51  [INFO] Results:
16:34:51  [INFO] 
16:34:51  [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

And I see the results recorded:

https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-1729/2/testReport/org.eclipse.jdt.core.tests.model/JavaCoreStandaloneTest/

@iloveeclipse @jukzi 

I think this is ready to be merged.

**Comment by merks** [comment]
> > I think this is ready to be merged.
> 
> I believe org.eclipse.jdt.core.tests.model/test.xml need to be updated, so the test is also executed on "official" SDK build and not only on jenkins.

I believe that updating the test.xml requires someone who speaks Antinese, but I don't know Antinese. I know Java, and I know Maven/Tycho, but not Antinese.  Perhaps this is why @jukzi was not willing or able to add such a test after having authored it.   Unfortunately I'm literally unable to jump this particular hurdle.   Sorry.   Perhaps you know where to find a native Antinese speaker who can assist on this details?  In any case, it seems better to have a test that fails only for validation builds than to have no test at all.

**Comment by jukzi** [comment]
i verified i see the testresult on jenkins - that should be enough to be an improvement. 
image
it also opens the possiblilty to add further standalone tests. thanks Ed,
please have a look on next i-build if it was executed there too.

**Pull request merged**
