### PR TITLE
jclMin22.jar contains classes compiled against Java 21

### PR DESCRIPTION
**Pull request by iloveeclipse**
Re-built jclMin22.jar from jclMin22src.jar with proper project compilation target and enabled test232816f().

Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2580

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@laeubi : any idea where this is coming from:

```
ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.8:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jdt.core.compiler.batch: Baseline and reactor have the same fully qualified version, but different content
18:40:45  [ERROR] different
18:40:45  [ERROR]    META-INF/ECLIPSE_.RSA: not present in baseline
18:40:45  [ERROR]    META-INF/ECLIPSE_.SF: not present in baseline
```

Does it mean, ecj is not signed in the 4.33?

**Comment by laeubi** [comment]
According to the log the jar was replaced with the baseline so there should be no baseline diff. Maybe this needs a rebase on master now some settings have changed?

**Comment by iloveeclipse** [comment]
> According to the log the jar was replaced with the baseline so there should be no baseline diff. Maybe this needs a rebase on master now some settings have changed?

Isn't the error about different content between baseline and reactor? I'm sure this commit is on top of master.

**Comment by laeubi** [comment]
> Isn't the error about different content between baseline and reactor? 

Yes but the logfile says that the main artifact (of the reactor) was replaced, what makes sense as you do not changed anything for ECJ (as far as I can see), so the error is really unexpected.

And thats also what the error complains, it says the jars have the _exact same version_ but different contents...

While on this one https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2911/2/console

it complains that only qualifier changed (what usually indicates a missing version bump).

**Pull request merged**
