### PR TITLE
Eclipse 2024-03 reports unclosed closeable for whitelisted StreamEx

### PR DESCRIPTION
**Pull request by stephan-herrmann**
tests #2191

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
Mmmhhh,

>[testStreamEx_GH2919 - 1.8](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2199/1/testReport/org.eclipse.jdt.core.tests.compiler.regression/ResourceLeakTests/testStreamEx_GH2919___1_8)	14 ms	Passed
>[testStreamEx_GH2919 - 11](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2199/1/testReport/org.eclipse.jdt.core.tests.compiler.regression/ResourceLeakTests/testStreamEx_GH2919___11)	11 ms	Passed
>[testStreamEx_GH2919 - 17](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2199/1/testReport/org.eclipse.jdt.core.tests.compiler.regression/ResourceLeakTests/testStreamEx_GH2919___17)	11 ms	Passed
>[testStreamEx_GH2919 - 21](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2199/1/testReport/org.eclipse.jdt.core.tests.compiler.regression/ResourceLeakTests/testStreamEx_GH2919___21)	13 ms	Passed
>[testStreamEx_GH2919 - 22](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2199/1/testReport/org.eclipse.jdt.core.tests.compiler.regression/ResourceLeakTests/testStreamEx_GH2919___22)	14 ms	Passed

@szarnekow do you see any difference between my test and your use case?

**Comment by szarnekow** [comment]
@stephan-herrmann, thank you for investigating.

The error reproduces for me with this stub:

```
package one.util.streamex;

import java.util.Spliterator;
import java.util.function.Function;
import java.util.stream.BaseStream;
import java.util.stream.Stream;

public abstract class StreamEx<T> extends AbstractStreamEx<T, StreamEx<T>> {
	public static <T> StreamEx<T> of(T element) {
        return null;
    }
	public <R> StreamEx<R> flatMap(Function<? super T, ? extends Stream<? extends R>> mapper) {
        return null;
    }
}

abstract class AbstractStreamEx<T, S extends AbstractStreamEx<T, S>> extends
BaseStreamEx<T, Stream<T>, Spliterator<T>, S> implements Stream<T>, Iterable<T> {
	@Override
	public Spliterator<T> spliterator() {
		return null;
	}
}
abstract class BaseStreamEx<T, S extends BaseStream<T, S>, SPLTR extends Spliterator<T>, B extends BaseStreamEx<T, S, SPLTR, B>>
implements BaseStream<T, S> {
}
```

The test case can subsequently be simplified to
```java
import one.util.streamex.StreamEx;
class Issue2191 {
	void whoot(Object obj) {
		// Potential resource leak: '<unassigned Closeable value>' may not be closed
		StreamEx.of(obj).toString();
	}
```
and 
```java
package one.util.streamex;

import java.util.Spliterator;
import java.util.function.Function;
import java.util.stream.Stream;

public abstract class StreamEx<T> extends Base<T> {
	public static <T> StreamEx<T> of(T element) {
		return null;
	}
}

abstract class Base<T> implements Stream<T> {
}
```

If we make the case a tiny bit more interesting:
```java
package one.util.streamex;

import java.util.Spliterator;
import java.util.function.Function;
import java.util.stream.Stream;

public abstract class StreamEx<T> extends Base<T> {
	public static <T> StreamEx<T> of(T element) {
		return null;
	}

	public static <T> StreamEx<T> of(Spliterator<? extends T> spliterator) {
		return null;
	}

	@Override
	public <R> StreamEx<R> flatMap(Function<? super T, ? extends Stream<? extends R>> mapper) {
		return null;
	}

	public StreamEx<T> append(Stream<? extends T> other) {
		return null;
	}
}

abstract class Base<T> implements Stream<T> {
}
```

another warning pops up
```
import java.util.Spliterator;

import one.util.streamex.StreamEx;

class Issue2191 {
	Object puzzling(Object obj) {
		// Potential resource leak: '<unassigned Closeable value>' may not be closed
		return StreamEx.of(obj)
		.flatMap(container -> 
			// Resource leak: '<unassigned Closeable value>' is never closed
			StreamEx
				.of((Spliterator<Object>)null)
				.append(
						// Mandatory close of resource '<unassigned Closeable value>' has not been shown
						StreamEx.of((Spliterator<Object>)null)));
	}
}
```

The compiler settings I used:

Screenshot 2024-03-22 at 09 32 34

[issue2191.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14719930/issue2191.zip)

**Comment by stephan-herrmann** [comment]
```diff
-	public abstract class StreamEx<T> implements Stream<T> {
+	public abstract class StreamEx<T> extends AbstractStreamEx<T, StreamEx<T>> {
```

Guess what: this innocent diff revealed a real blooper in our existing whitelist detection: 
* we have separate methods for detecting white listed _interfaces_ vs _classes_
* these methods are invoked when superclass or superInterfaces are resolved respectively
* the methods, however, don't even look at a superclass or interface, but at the *current* type.

For source types the solution is simple: invoke the appropriate variant during `connectTypeHierarch()` (after super type resolving may have set `BitAutoCloseable`). 

For binary types and parameterized types I didn't (yet) change the wiring into `superclass()` and `superInterfaces()`. The effect is that white list detection may happen twice (once from each method), but since the method is fast, and double invocation should not cause any harm, I'm leaving it at that for now.

**Comment by stephan-herrmann** [comment]
Test failure is #2187

**Comment by szarnekow** [comment]
@stephan-herrmann I installed the Eclipse batch compiler for Java from this update site: https://download.eclipse.org/eclipse/updates/4.32-I-builds/I20240403-0940/plugins/

I still see the same errors for usages of StreamEx. Should that build contain the fix?

**Comment by szarnekow** [comment]
Ah, it seems I've to install the Eclipse Java Development Tools instead.

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann I installed the Eclipse batch compiler for Java from this update site: https://download.eclipse.org/eclipse/updates/4.32-I-builds/I20240403-0940/plugins/

How can you use a plugins directory as an update site? For me that shows "No software site found at ..."

> Ah, it seems I've to install the Eclipse Java Development Tools instead.

Did that help?

**Comment by szarnekow** [comment]
@stephan-herrmann Yes, this helped.

Note that I used the wrong link (plugins subdir), I tried installing the batch compiler alone from the update site, but had to choose the correct feature. My bad. Everything's gucci now.

**Pull request merged**
