### PR TITLE
Provide an API to check if an IType is an implicitly declared class.

### PR DESCRIPTION
**Pull request by datho7561**
## What it does
Provide an API to check if an `IType` is an implicitly declared class.

## How to test
I've included a test case. The only way to manually test this would be to consume the API.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by datho7561** [comment]
That's why there aren't any new test failures, then!

I saw that I was still removing the message format and assumed I was still making that change in this commit.

The test failure seems unrelated, and is present in `master`

**Comment by datho7561** [comment]
@jarthana @jjohnstn @rgrunber if you have time, could you please take a look at this PR?

**Comment by rgrunber** [comment]
Is there any reason to do a minor bump on `org.eclipse.jdt.core.tests.builder` & `org.eclipse.jdt.core.tests.compiler` ? Doesn't seem anything was changed there.

**Comment by datho7561** [comment]
> Is there any reason to do a minor bump on `org.eclipse.jdt.core.tests.builder` & `org.eclipse.jdt.core.tests.compiler` ? Doesn't seem anything was changed there.

I'll try removing the bump

**Comment by srikanth-sankaran** [comment]
Given the nomenclature change to implicitly declared classes, should we be using a mixture of "unnamed" and "implicitly declared" internally ? Does it serve a purpose ?

**Comment by rgrunber** [comment]
It might make sense to just use "unnamed". The underlying implementation seems to be tied to unnamed classes. It wouldn't help someone determine if a class was generated by Lombok, but it might have consumers of the API wrongly thinking it might.

**Comment by srikanth-sankaran** [comment]
Not sure I understand. "Unnamed classes" was old terminology. Subsequent JEP changed it to Implicitly declared classes - no ? So why would it be useful to continue to refer to withdrawn nomenclature ??

**Comment by rgrunber** [comment]
Whoops, I overlooked the ["changed to implicitly declared classes"](https://openjdk.org/jeps/463) in your comment. Thought you were only implying the new API should change to match the existing "unnamed classes" one. It definitely makes sense to use the new terminology going forward.

**Comment by datho7561** [comment]
I think we should use "implicitly declared class" consistently. I wasn't sure whether or not to make that change to the API AST node as a part of this PR, so I left it unchanged.

**Pull request merged**
