### PR TITLE
Junit4 test finder fails to find tests in modular Java project

### PR DESCRIPTION
**Pull request by trancexpress**
The fix for #675 introduces a regression, since the JUnit container is not marked as modular. The search for JUnit types (e.g. `org.junit.Test`) however depends on the modular info attached for the `PackageFragmentRoot` of the JUnit container.

This change adjusts the fix for #675 to assume a modular container, if the Java project is modular.

Fixes: #1039

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by trancexpress** [comment]
I really don't know about this. From my POV its correct to assume JUnit is not on the module path, in the given situation. What the JDT search does with this fix (and before changes for #675), is add everything from the JUnit container to the module of the Java project... that can't be right, since the JUnit container itself has no modules...

But I don't find a simple way to add the contents of the container to the unnamed module. With the bugs we have fixed so far in this area, we only cared about source folders and jar libraries. If we run into search problems for containers (which is not unlikely) I guess we'll have to revisit this fix.

**Comment by iloveeclipse** [comment]
> From my POV its correct to assume JUnit is not on the module path, in the given situation. What the JDT search does with this fix (and before changes for #675), is add everything from the JUnit container to the module of the Java project... that can't be right, since everything in the JUnit container doesn't define modules...

This is my opinion too. If we move JUnit to the module path (and update module dependency to junit), the test is found.

> But I don't find a simple way to add the contents of the container to the unnamed module

Then we probably need a complicated way :-)

**Comment by iloveeclipse** [comment]
Converted PR to draft for now.

**Comment by trancexpress** [comment]
> Converted PR to draft for now.

From my POV better to merge as is, to fix the regression from #675. We can add a TODO to try to find a better way to fix the original bug (adding the container on the module path, even though it doesn't have modular libraries).

**Comment by iloveeclipse** [comment]
> > Converted PR to draft for now.
> 
> From my POV better to merge as is, to fix the regression from #675. We can add a TODO to try to find a better way to fix the original bug (adding the container on the module path, even though it doesn't have modular libraries).

I'm not convinced that the fix here is correct. The JUnit container **is** on classpath but **not** on module path. The fix puts it to the later one (or does something similar answering "yes" from `isOnModulePath()`), which is questionable and will most likely break other cases again.

**Comment by trancexpress** [comment]
> The fix puts it to the later one (or does something similar answering "yes" from `isOnModulePath()`), which is questionable and will most likely break other cases again.

The only thing the change does is disable the fix for #675 in the case of containers, in case of a modular project. Do you actually care for call hierarchy working (w.r.t. #675) those cases?

> I'm not convinced that the fix here is correct.

I don't imagine another fix is coming soon.

**Comment by basilevs** [comment]
Eclipse PDE uses a container for plug-in  dependencies. Call-hierarchy being glitchy there is quite annoying. Will PDE work?

**Comment by iloveeclipse** [comment]
Superceeded by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1066

**Pull request closed without merging**
