### PR TITLE
 AssertionError at org.eclipse.jdt.internal.compiler.ast.YieldStatement.addSecretYieldResultValue(YieldStatement.java:120) 

### PR DESCRIPTION
**Pull request by srikanth-sankaran**
## What it does

Resolve the yield statement in its enclosing scope.
Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1835

## Author checklist

- [ ] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by srikanth-sankaran** [comment]
The concerned assert got introduced in the fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=545567 and appears suspect.

Here is the relevant code in `org.eclipse.jdt.internal.compiler.ast.YieldStatement.addSecretYieldResultValue(BlockScope)`

```
         SwitchExpression se = this.switchExpression;
                             ...
                             ...
         assert se.yieldResolvedPosition >= 0;
	local.resolvedPosition = se.yieldResolvedPosition;
	assert local.resolvedPosition < this.scope.maxOffset;
```

The problem is that `org.eclipse.jdt.internal.compiler.ast.SwitchExpression.yieldResolvedPosition` gets assigned in `org.eclipse.jdt.internal.compiler.ast.SwitchExpression.processTypesBindingsOnStack(CodeStream)` which works with the scope associated with the `SwitchExpression`.

But a `YieldStatement` gets its own subscope in `org.eclipse.jdt.internal.compiler.ast.YieldStatement.resolve(BlockScope)` thusly:

```
private boolean isInsideTry() {
	return this.switchExpression != null && this.switchExpression.containsTry;
}
@Override
public void resolve(BlockScope skope) {
	this.scope = isInsideTry() ? new BlockScope(skope) : skope;
```

In the present test case, `isInsideTry()` is true and so YieldStatements are assigned a subscope of `SwitchExpression`'s scope.

But the assert is asserting that a resolved position computed wrt to a parent scope is within a subscope of the parent.

Something amiss there.

I see three possible fixes:

1. Is the assert really adding value ? If not get rid of it.
2. Compare the proper scopes by also checking for  `isInsideTry()` inside `YieldStatement.addSecretYieldResultValue` 
3. Resolve YieldStatements in the same enclosing scope instead of creating a subscope.

In the PR, I am taking approach 3. All tests are green - So it is unclear what the motivation for creating a subscope for yield statements is - @mpalat can you shed some light on this ??

**Comment by srikanth-sankaran** [comment]
@mpalat - Can you review this please ?? Is getting rid of the subscope creation violates some design intent ??

Could you also take a look at the code generated for the minimal test case and confirm it meets expectations ? 

TIA

**Comment by mpalat** [comment]
> @mpalat - Can you review this please ?? Is getting rid of the subscope creation violates some design intent ??

@srikanth-sankaran will try to recollect (its been sometime) but I believe this is documented in detail in the bug - please take a look at https://bugs.eclipse.org/bugs/show_bug.cgi?id=545567#c20 - specifically this line "currently in the patch it is upper scope of switch expression - ideally I think it should be in the switch expression scope since multiple sibling switch expressions in a block will have conflict" - I believe this was the design intent to have subscopes - I don't have a ready-made example for this though.

**Comment by srikanth-sankaran** [comment]
> > @mpalat - Can you review this please ?? Is getting rid of the subscope creation violates some design intent ??
> 
> @srikanth-sankaran will try to recollect (its been sometime) but I believe this is documented in the bug - please take a look at https://bugs.eclipse.org/bugs/show_bug.cgi?id=545567#c20 - specifically this line "currently in the patch it is upper scope of switch expression - ideally I think it should be in the switch expression scope since multiple sibling switch expressions in a block will have conflict" - I believe this was the design intent to have subscopes - no I don't have an example demonstrating this issue. Tried out a few scenarios, but they are working with your PR. So I believe, this subscoping was not required - +1 for removing the subscope.

@mpalat on master the secret variable is added to the switch expression's scope only and not to its upperscope. I say this because in `org.eclipse.jdt.internal.compiler.ast.SwitchStatement.resolve(BlockScope)` I see the following: 

```
			addSecretPatternSwitchVariables(upperScope);
			if (this.statements != null) {
				if (this.scope == null)
					this.scope = new BlockScope(upperScope);
```

So, if the switch expression has a body at all, it gets its own scope. _It has to!_ Anything declared (named non-secret variables) inside switch's {} _cannot_ be added to its upper scope

And `org.eclipse.jdt.internal.compiler.ast.SwitchExpression.yieldResolvedPosition` is computed wrt to the scope of the switch expression in `org.eclipse.jdt.internal.compiler.ast.SwitchExpression.processTypesBindingsOnStack(CodeStream)` and it is only right that the secret variable should be added to the scope of the switch.

I have also pushed a commit, getting rid of the state `scope` in `YieldStatement` which was introduced for this express purpose.

**Review by mpalat — APPROVED** [review]
+1, Looks good - Thanks @srikanth-sankaran

**Comment by srikanth-sankaran** [comment]
> +1, Looks good - Thanks @srikanth-sankaran

Thank you!

**Pull request merged**
