### PR TITLE
Enhanced switch v2.0 - Part I

### PR DESCRIPTION
**Pull request by srikanth-sankaran**
* Reimplement resolution, analysis and bookkeeping involved with `CaseStatement` and resolution of `SwitchStatement` for a streamlined and cleaner implementation resulting in readily obvious control flow and minimization of state.
* Report non-constant label expressions during resolution rather than waiting for flow analysis phase.
* Change how duplicate label expressions are reported. Don't blame the whole case, just the duplicate expression; Don't blame the original, just the duplicate.
* Represent qualified enumerators with qualified names internally so to avoid name clashes
* Eliminate the hack to inject synthetic `BreakStatement` in label rule switch blocks. Enhance the code generator to handle these explicitly.
* Simplify the implementation of SwitchStatement.getFallThroughState correcting various issues.
* Eliminate the unnecessary vector `SwitchStatement.constMapping` that is passed to `org.eclipse.jdt.internal.compiler.codegen.CodeStream.tableswitch` - constanMapping[i] == i always!
* Enable various tests in `PrimitiveInPatternsTest.java` that were disabled, fixing broken tests; Remove their disabled cousins from `PrimitiveInPatternsTestSH.java`
* Add a disabled regression test for #3319 (not yet understood/fixed)
* Numerous defect fixes as listed below

* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3336
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3318
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3320
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3321
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3334
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3335
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3265
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3169
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3339
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3337
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3344

### CODE REVIEW

**Comment by akurtakov** [comment]
Do we expect comparator issues coming from this one? If yes, I would rather start an I-build now so  they can be looked at today.

**Comment by srikanth-sankaran** [comment]
> Do we expect comparator issues coming from this one? If yes, I would rather start an I-build now so they can be looked at today.

I doubt it - there are _some_ class file and code generation changes _for sure_ particularly in the context of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3321 but that likely affects only Java 21 sources. 

That we didn't see any comparator issues in jdt's own CI build is a sign.

All that said, this is a massive, near complete rewrite of various portions of switch/case handling. 
Why don't we get started sooner - yes, please trigger an I-Build now so we will know for sure. 

Thanks very much @akurtakov

**Comment by akurtakov** [comment]
Here it is https://ci.eclipse.org/releng/job/Builds/job/I-build-4.35/4/

**Comment by srikanth-sankaran** [comment]
04:38:30  [ERROR] Cannot resolve dependencies of project org.eclipse.platform.feature:org.eclipse.platform:eclipse-feature:4.35.0-SNAPSHOT
04:38:30  [ERROR]  with context {osgi.os=linux, org.eclipse.update.install.features=true, osgi.arch=x86_64, org.eclipse.update.install.sources=true, osgi.ws=gtk, org.eclipse.jdt.buildtime=true}
04:38:30  [ERROR]   Software being installed: org.eclipse.platform.feature.group 4.35.0.qualifier
04:38:30  [ERROR]   Missing requirement: org.eclipse.help.feature.group 2.3.2100.v20241126-0613 requires 'org.eclipse.equinox.p2.iu; org.eclipse.help.base [4.4.700.v20241126-0110,4.4.700.v20241126-0110]' but it could not be found
04:38:30  [ERROR]   Cannot satisfy dependency: org.eclipse.platform.feature.group 4.35.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.help.feature.group 0.0.0: See log for details
04:38:30  [ERROR] -> [Help 1]

Not sure if this is the root problem

If a rebuild is triggered, we may as well include the commit https://github.com/srikanth-sankaran/eclipse.jdt.core/commit/1cf69bb93a37c5d1bf93a6c513fde9763b50c05c that just got merged -

**Comment by srikanth-sankaran** [comment]
> 04:38:30 [ERROR] Cannot resolve dependencies of project org.eclipse.platform.feature:org.eclipse.platform:eclipse-feature:4.35.0-SNAPSHOT 04:38:30 [ERROR] with context {osgi.os=linux, org.eclipse.update.install.features=true, osgi.arch=x86_64, org.eclipse.update.install.sources=true, osgi.ws=gtk, org.eclipse.jdt.buildtime=true} 04:38:30 [ERROR] Software being installed: org.eclipse.platform.feature.group 4.35.0.qualifier 04:38:30 [ERROR] Missing requirement: org.eclipse.help.feature.group 2.3.2100.v20241126-0613 requires 'org.eclipse.equinox.p2.iu; org.eclipse.help.base [4.4.700.v20241126-0110,4.4.700.v20241126-0110]' but it could not be found 04:38:30 [ERROR] Cannot satisfy dependency: org.eclipse.platform.feature.group 4.35.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.help.feature.group 0.0.0: See log for details 04:38:30 [ERROR] -> [Help 1]
> 
> Not sure if this is the root problem
> 
> If a rebuild is triggered, we may as well include the commit [srikanth-sankaran@1cf69bb](https://github.com/srikanth-sankaran/eclipse.jdt.core/commit/1cf69bb93a37c5d1bf93a6c513fde9763b50c05c) that just got merged -

I meant this commit: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/1cf69bb93a37c5d1bf93a6c513fde9763b50c05c

**Comment by srikanth-sankaran** [comment]
@akurtakov - I am not familiar with the build set up so unable to analyze the next steps ...

**Comment by akurtakov** [comment]
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.35/6/consoleFull went beyond the previous failures. For the record - I-builds always use master of all submodules so this commit should be included in this build.

**Comment by HannesWell** [comment]
> > Git patch
> > Further information are available in [Common Build Issues - Missing version increments](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/wiki/Common-Build-Issues#missing-version-increments).
> 
> @HannesWell , I hear from @iloveeclipse that this automatic increment of versions in the new development cycle is your contribution. It used to irritate me to have to do that manually - thank you so much for this feature 👍 👏

You are very welcome and thanks for the nice words. I'm glad it it's helpful. :)
But you also have to thank @laeubi who created the foundations in Tycho on top of which the workflows are built.

**Comment by srikanth-sankaran** [comment]
Thanks to you too @laeubi 👍

**Pull request merged**
