### PR TITLE
Bug 579205 - java indexer became slower

### PR DESCRIPTION
**Pull request by stephan-herrmann**
Withdraw all .eea handling from JavaSearchNameEnvironment

Plus: add robustness to ExternalAnnotations18Test run at compliance=11

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
@jarthana , @iloveeclipse I'd like to merge this if tests pass, but I don't know what to do about the downvote from Check Code Freeze Period. For one, I didn't expect it to trigger today already. Secondly, if merging is still allowed, I don't know the ceremony for overriding that check.

**Comment by iloveeclipse** [comment]
Just merge if you are sure, no ceremony here.

**Comment by iloveeclipse** [comment]
@stephan-herrmann : could this be that we should also update Java 17 tests?
See https://download.eclipse.org/eclipse/downloads/drops4/I20220516-0600/testresults/html/org.eclipse.jdt.core.tests.model_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
Unexpected markers. ----------- Expected ------------ Null type mismatch: required '@NonNull Object' but the provided value is null\n Null type mismatch: required '@NonNull Test1' but the provided value is null\n Potential null pointer access: The variable v may be null at this location ------------ but was ------------ Null type mismatch: required '@NonNull Object' but the provided value is null\n Null type mismatch: required '@NonNull Test1' but the provided value is null --------- Difference is ---------- expected:<...ovided value is null[\n Potential null pointer access: The variable v may be null at this location]> but was:<...ovided value is null[]>

junit.framework.ComparisonFailure: Unexpected markers.
----------- Expected ------------
Null type mismatch: required '@NonNull Object' but the provided value is null\n
Null type mismatch: required '@NonNull Test1' but the provided value is null\n
Potential null pointer access: The variable v may be null at this location
------------ but was ------------
Null type mismatch: required '@NonNull Object' but the provided value is null\n
Null type mismatch: required '@NonNull Test1' but the provided value is null
--------- Difference is ----------
expected:<...ovided value is null[\n
Potential null pointer access: The variable v may be null at this location]> but was:<...ovided value is null[]>
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:266)
at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
at org.eclipse.jdt.core.tests.model.AbstractJavaModelTests.assertMarkers(AbstractJavaModelTests.java:1064)
at org.eclipse.jdt.core.tests.model.ExternalAnnotations17Test.test1FullBuildWithVariable(ExternalAnnotations17Test.java:119)
```

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann : could this be that we should also update Java 17 tests? See https://download.eclipse.org/eclipse/downloads/drops4/I20220516-0600/testresults/html/org.eclipse.jdt.core.tests.model_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

FYI: ExternalAnnotations17Test is not about Java 17 but Java 1.7 :)

Given that the same test passed on another platform, I guess this is unrelated, but I'll check it later today.

**Comment by stephan-herrmann** [comment]
> Given that the same test passed on another platform, I guess this is unrelated, but I'll check it later today.

I tried running this in different contexts: JDK versions, standalone vs. AllJavaModelTests and could not reproduce locally. Nor does it smell like anything I recently touched. Not much I can do.

@iloveeclipse Do let me know, though, if it happens again.

**Pull request merged**
