### PR TITLE
Use Java 23 in Jenkinsfile

### PR DESCRIPTION
**Pull request by mickaelistria**
## What it does

Updates Jenkinsfile to test against Java 23

## How to test

Just let CI do the job.

## Author checklist

- [ ] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by akurtakov** [comment]
@iloveeclipse WDYT?

**Comment by iloveeclipse** [comment]
I'm out of PC now, the tests are failing because of Java 23?

There are at least two issues known with Java 23, both affect JDT, @stephan-herrmann : WDYT?

**Comment by stephan-herrmann** [comment]
> I'm out of PC now, the tests are failing because of Java 23?

This PR failed at org.eclipse.jdt.core.tests.builder.BuildpathTests.testChangeZIPArchive1 which does not hint at a Java 23 issue.

> There are at least two issues known with Java 23, both affect JDT, @stephan-herrmann : WDYT?

Which known issues are you referring to? The JIT bug, or the other JVM bug since 18 surfacing in JavaLeakTests? Or ...?

**Comment by stephan-herrmann** [comment]
Generally I very much appreciate running builds / tests on Java 23.

**Comment by jukzi** [comment]
CI succeeded  with  openjdk 21.0.2+13-58
```
[2024-09-25T14:34:46.349Z] + java -version
[2024-09-25T14:34:46.349Z] openjdk version "21.0.2" 2024-01-16
[2024-09-25T14:34:46.349Z] OpenJDK Runtime Environment (build 21.0.2+13-58)
[2024-09-25T14:34:46.349Z] OpenJDK 64-Bit Server VM (build 21.0.2+13-58, mixed mode, sharing)
```

**Comment by jukzi** [comment]
> 21.0.2+13-58

oh, but you configured 23, why did it not run with 21? maybe permission missing for author. lets see what master does.

**Comment by jukzi** [comment]
master runs now with  23+37-2369
```
11:22:23  + java -version
11:22:23  openjdk version "23" 2024-09-17
11:22:23  OpenJDK Runtime Environment (build 23+37-2369)
11:22:23  OpenJDK 64-Bit Server VM (build 23+37-2369, mixed mode, sharing)
11:22:23  + mkdir -p /home/jenkins/agent/workspace/eclipse.jdt.core-Github_master/tmp
```
https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/master/384/timestamps/?time=HH:mm:ss&timeZone=GMT+2&appendLog&locale=en_US

**Comment by jukzi** [comment]
master shows now 2 failing tests:
```
 org.eclipse.jdt.core.tests.compiler.regression.PatternMatching16Test.test019 - 17
 org.eclipse.jdt.core.tests.builder.BuildpathTests.testChangeZIPArchive1
```

"testChangeZIPArchive1" already failed in this PR with java 21, so it is unrelated.
I don't see a issue reported for "PatternMatching16Test" yet. @mickaelistria would you mind to investigate?

**Comment by jukzi** [comment]
https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/master/385/ passed

**Pull request merged**
