### PR TITLE
Enable potential resource leak analysis, fix unmanaged streams

### PR DESCRIPTION
**Pull request by jukzi**
fixes
"At least one of the problems in category 'resource' is not analysed due
to a compiler option being ignored"

"Potential resource leak: '<unassigned Closeable value>' may not be
closed"

https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1946

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
@jukzi I saw your review request and I would have loved to discuss this, but I simply didn't find the time at short notice. Please remember that I work on Eclipse entirely in my spare time.

So you killed the idea to enforce a closing-protocol on ProblemReporter, huh? I admit this wasn't quite mature yet, but why the haste? At least the javadoc of ProblemReporter.close() should be synced with the code, either way.

**Comment by jukzi** [comment]
Silence is no clear indicator - When you don't find the time to review, but plan to review later, please leave a short notice. I removed the autoclosable since 1. it did not cover a system resource 2. autocloseable enforced nothing but only gave a warning 3. it introduced so many warnings that you disabled the warnings which also removed unrelated relevant warnings. 
Please adjust javadoc as you want, or even re-add autoclosable if you can do it without disabling the warnings.

**Comment by stephan-herrmann** [comment]
> Please adjust javadoc as you want

It was consistent before your change, suggesting t-w-r is wrong due to your change.

**Comment by jukzi** [comment]
> suggesting t-w-r is wrong due to your change.

ok, i will fix that. thanks for the hint

**Comment by jukzi** [comment]
see https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1988

**Pull request merged**
