### PR TITLE
Generate reference to classes holding constants used in the code

### LINKED ISSUE #1382: Generate reference to classes holding constants used in the code
Originally https://bugs.eclipse.org/bugs/show_bug.cgi?id=549455

We learned that https://bugs.openjdk.org/browse/JDK-7153958 deliberately made javac emit unnecessary CONSTANT_Class entries in class files, to record "dependencies" on classes of which constants have been inlined in the code.

This creates a hidden contract between javac and tools consuming that entry for their analysis, so it should have been driven by a spec change rather than an unannounced implementation change, but given that the change is close to trivial, ecj might as well follow suit.

### PR DESCRIPTION
**Pull request by stephan-herrmann**
fixes #1382

Emit a class constant into the constant pool for every class from which a constant is used.

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
@iloveeclipse  results from API-Tools signal bytecode changes, indeed. This could cause quite a landslide of comparator errors in the SDK build. Please suggest how / when to proceed.

As mentioned in the issue #1382  this will eliminate one small difference wrt javac.

**Comment by iloveeclipse** [comment]
@stephan-herrmann : 
1) we can merge this and build SDK now to get the list of (most likely all) affected bundles. 
2) After that one should create ticket for unstable SDK build at https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues and check if our expectation **why** the unstable build is unstable matches the class file diffs (there should be this change in constant pool only).
3) After that for every bundle that is reported to be "unstable" one has to "touch" it, set a PR and merge.
The work of touching bundles is boring, but can be automated via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/wiki/Platform-Releng-Faq#how-to-fix-unstable-build
4) After that we can start next SDK build to validate everything is touched and stable.

So if you are confident in this PR, feel free to merge and we can continue with points above.

**Comment by iloveeclipse** [comment]
Actually you can touch affected JDT bundles already that make this PR red as of now.

**Comment by iloveeclipse** [comment]
@stephan-herrmann : if you plan to merge it today, please do it before 00:00 CET so the next build can pick it and we can start looking into "touching" bundles tomorrow without extra build.

**Comment by stephan-herrmann** [comment]
> Actually you can touch affected JDT bundles already that make this PR red as of now.

done

> if you plan to merge it today, please do it before 00:00 CET so the next build can pick it and we can start looking into "touching" bundles tomorrow without extra build.

At that time I was already offline, and in fact I thought better not to mess up a Monday build (as those are the ones retained longer than other days, right?) - but then I got my timezone arithmetic wrong, so perhaps _now_ I should indeed wait until the Monday build it good.

**Comment by iloveeclipse** [comment]
@stephan-herrmann : just merge if you are done, if you wish, now. I can help next day to fix the SDK build.

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann : just merge if you are done, if you wish, now. I can help next day to fix the SDK build.

Thanks!

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1979.

**Pull request merged**
