### PR TITLE
JEP 455: instanceof involving boxing & test reorganization

### PR DESCRIPTION
**Pull request by stephan-herrmann**
Implementation:
* boxing plus widening reference conversions
* boxing in patterns
 
Testing:
* generic complete tests for primitive widening & narrowing
* generic tests for tests involving boxing
* enable run.javac with 23-ea

based on #2549 (squashed and rebased).

addresses https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2298

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
@mpalat here is a proposal that might replace #2549, containing these changes:
* slight implementation clarification, see https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2549/commits/432b4118f9dc81950c0876f52e582f506de095c0
* test re-organization: fold lots of plain tests into a few generic tests
  * IMHO this makes it easier to vouch for complete coverage
  * tests run significantly faster (because launching each individual test is costly).

@srikanth-sankaran do you want to comment on the strategy for tests? I'm aware that typically tests should be straight forward to challenge exactly one thing at a time with little risk of messing up by complexity in the test code. In this case I simply lost track among 100+ tests, that all looked very similar. That's why I figured that something like matrix testing (widen all primitives to all applicable other primitives etc. multiplied with different styles of instanceof expressions) might rather be programmed than enumerated explicitly. Are you fine with this style?

**Comment by mpalat** [comment]
@stephan-herrmann my personal preference would be to have the test in the original form such that it tests only one part. However, since @srikanth-sankaran wants to own this feature later, will wait for his take.

**Comment by stephan-herrmann** [comment]
> [...] such that it tests only one part.

I won't object to that aim, but we seem to disagree on what is "one part". Where I see one test case (e.g.: test primitive identity conversions) you seem to see 24(!) relevantly different tests. One way or other, I think we do need more structure to have at least some chance to detect duplicate tests and omissions.

> However, since @srikanth-sankaran wants to own this feature later, will wait for his take.

:+1:

**Comment by stephan-herrmann** [comment]
Some code changes have been merged via other PRs, comments on the code are (a) moved to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2880, (b) no longer relevant.

Re-organized tests have been merged additionally in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2878

We're done.

**Pull request closed without merging**
