### PR TITLE
configure default output.. = bin/

### PR DESCRIPTION
**Pull request by jukzi**

### CODE REVIEW

**Comment by akurtakov** [comment]
Please try not to push PRs that fail validation. This creates extra work on releng side https://download.eclipse.org/eclipse/downloads/drops4/I20231130-0020/buildlogs/reporeports/reports/versionChecks.html shows org.eclipse.jdt.annotation.source needing version bump. Please fix asap.

**Comment by jukzi** [comment]
which verification fail?
image

**Comment by akurtakov** [comment]
I stand corrected, sorry ! The fault is actually that the bundle has been skipped.  https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1652 should fix this.

**Comment by akurtakov** [comment]
Version fixed and verification build should catch it next time. Sorry again for blaming you.

**Pull request merged**
