### PR TITLE
Add some generics to org.eclipse.jdt.internal.core

### PR DESCRIPTION
**Pull request by mickaelistria**
## What it does

Add some generics to org.eclipse.jdt.internal.core

## How to test

Just ensure it doesn't cause regression nor adds new warnings

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by mickaelistria** [comment]
@jukzi Would you be OK to review/merge this one?

**Comment by jukzi** [comment]
will do tomorrow

**Comment by jukzi** [comment]
there was a similar commit which now introduced conflicts, please fix. in general the PR looks god to me

**Comment by mickaelistria** [comment]
OK cool. I think this patch is not useful anymore; thanks for the other one, that's very helpful!

**Pull request closed without merging**
