### PR TITLE
Use meta index for reference search

### PR DESCRIPTION
**Pull request by gayanper**
## What it does
The meta index which was introduced to speedup subtype search could be used to speed up the reference search as well. When proper qualifier parameters are given with the pattern, the index selection will use that information to narrow down the correct indexes to search for.

This change will only add support for using meta index information for type reference and declaration search for now.

## How to test
- Integration tests which exist for Java Search must pass without any changes needed.
- Person type reference and declaration search in the IDE.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by gayanper** [comment]
please rebuild

**Comment by gayanper** [comment]
@iloveeclipse let me know if you have time to check this change. I would like to get this merged as well so we can find any issue sooner. The change is verified by existing tests which proves by the previous failure we got due to meta indexing issue #533

**Comment by gayanper** [comment]
Seems like my accidentally pushed branch has cause the build url not to work properly. Here is the correct PR build https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/view/change-requests/job/PR-532/

**Comment by gayanper** [comment]
@testforstephen will help me to check on this PR as well ? You read about meta index here https://wiki.eclipse.org/JDT_Core_Programmer_Guide/MetaIndex

**Comment by testforstephen** [comment]
> @testforstephen will help me to check on this PR as well ? You read about meta index here https://wiki.eclipse.org/JDT_Core_Programmer_Guide/MetaIndex

YES, I can have a look. Recently I'm working on supporting shared index across workspaces, metaindex might have an impact on that feature as well. I will take a look at the metaindex implementation.

**Pull request merged**
