### PR TITLE
ECJ records canonical constructor signature is not generated. Fixes #365

### LINKED ISSUE #365: ECJ records canonical constructor signature is not generated if a secondary constructor is present
If a record definition contains a secondary record, the generic signature for the canonical constructor is not generated by ECJ. 
Using the adotium JDK compiler, instead, the generic signature is generated.
For example:
```java
public record A(List<String> names) {}
```
generates the following bytecode:
```
// Compiled from A.java (version 17 : 61.0, super bit)
public final record A extends java.lang.Record {
  
  // Field descriptor #6 Ljava/util/List;
  // Signature: Ljava/util/List<Ljava/lang/String;>;
  private final java.util.List names;
  
  // Method descriptor #10 (Ljava/util/List;)V
  // Signature: (Ljava/util/List<Ljava/lang/String;>;)V  <--- Generic signature is generated
  // Stack: 2, Locals: 2
  public A(java.util.List names);
     0  aload_0 [this]
     1  invokespecial java.lang.Record() [13]
     4  aload_0 [this]
     5  aload_1 [names]
     6  putfield A.names : java.util.List [16]
     9  return
      Line numbers:
        [pc: 0, line: 4]
      Local variable table:
        [pc: 0, pc: 10] local: this index: 0 type: A
        [pc: 0, pc: 10] local: names index: 1 type: java.util.List
      Local variable type table:
        [pc: 0, pc: 10] local: names index: 1 type: java.util.List<java.lang.String>
      Method Parameters:
        names
  
  // Method descriptor #24 ()Ljava/util/List;
  // Signature: ()Ljava/util/List<Ljava/lang/String;>;
  // Stack: 1, Locals: 1
  public java.util.List names();
    0  aload_0 [this]
    1  getfield A.names : java.util.List [16]
    4  areturn
      Line numbers:
        [pc: 0, line: 4]
  
  // Method descriptor #27 ()Ljava/lang/String;
  // Stack: 2, Locals: 1
  public final java.lang.String toString();
    0  aload_0 [this]
    1  invokedynamic 0 toString(A) : java.lang.String [28]
    6  areturn
      Line numbers:
        [pc: 0, line: 1]
  
  // Method descriptor #32 ()I
  // Stack: 2, Locals: 1
  public final int hashCode();
    0  aload_0 [this]
    1  invokedynamic 0 hashCode(A) : int [33]
    6  ireturn
      Line numbers:
        [pc: 0, line: 1]
  
  // Method descriptor #37 (Ljava/lang/Object;)Z
  // Stack: 2, Locals: 2
  public final boolean equals(java.lang.Object arg0);
    0  aload_0 [this]
    1  aload_1 [arg0]
    2  invokedynamic 0 equals(A, java.lang.Object) : boolean [38]
    7  ireturn
      Line numbers:
        [pc: 0, line: 1]

  Inner classes:
    [inner class info: #54 java/lang/invoke/MethodHandles$Lookup, outer class info: #56 java/lang/invoke/MethodHandles
     inner name: #58 Lookup, accessflags: 25 public static final]

Record: #Record
Components:
  
// Component descriptor #6 Ljava/util/List;
// Signature: Ljava/util/List<Ljava/lang/String;>;
java.util.List names;
Bootstrap methods:
  0 : # 50 invokestatic java/lang/runtime/ObjectMethods.bootstrap:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/TypeDescriptor;Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/invoke/MethodHandle;)Ljava/lang/Object;
	Method arguments:
		#1 A
		#51 names
		#52 REF_getField names:Ljava/util/List;
}
```
but if I have:
```java
public record A(List<String> names) {
	public A(String name) {
		this(Collections.singletonList(name));
	}
}
```
then the resulting bytecode is:
```
// Compiled from A.java (version 17 : 61.0, super bit)
public final record A extends java.lang.Record {
  
  // Field descriptor #6 Ljava/util/List;
  // Signature: Ljava/util/List<Ljava/lang/String;>;
  private final java.util.List names;
  
  // Method descriptor #10 (Ljava/lang/String;)V
  // Stack: 2, Locals: 2
  public A(java.lang.String name);
    0  aload_0 [this]
    1  aload_1 [name]
    2  invokestatic java.util.Collections.singletonList(java.lang.Object) : java.util.List [12]
    5  invokespecial A(java.util.List) [18]
    8  return
      Line numbers:
        [pc: 0, line: 6]
        [pc: 8, line: 7]
      Local variable table:
        [pc: 0, pc: 9] local: this index: 0 type: A
        [pc: 0, pc: 9] local: name index: 1 type: java.lang.String
      Method Parameters:
        name
  
  // Method descriptor #28 ()Ljava/util/List;
  // Signature: ()Ljava/util/List<Ljava/lang/String;>;
  // Stack: 1, Locals: 1
  public java.util.List names();
    0  aload_0 [this]
    1  getfield A.names : java.util.List [30]
    4  areturn
      Line numbers:
        [pc: 0, line: 4]
  
  // Method descriptor #33 ()Ljava/lang/String;
  // Stack: 2, Locals: 1
  public final java.lang.String toString();
    0  aload_0 [this]
    1  invokedynamic 0 toString(A) : java.lang.String [34]
    6  areturn
      Line numbers:
        [pc: 0, line: 1]
  
  // Method descriptor #38 ()I
  // Stack: 2, Locals: 1
  public final int hashCode();
    0  aload_0 [this]
    1  invokedynamic 0 hashCode(A) : int [39]
    6  ireturn
      Line numbers:
        [pc: 0, line: 1]
  
  // Method descriptor #43 (Ljava/lang/Object;)Z
  // Stack: 2, Locals: 2
  public final boolean equals(java.lang.Object arg0);
    0  aload_0 [this]
    1  aload_1 [arg0]
    2  invokedynamic 0 equals(A, java.lang.Object) : boolean [44]
    7  ireturn
      Line numbers:
        [pc: 0, line: 1]
  
  // Method descriptor #20 (Ljava/util/List;)V
  // Stack: 2, Locals: 2                                            <--- No generic signature generated
  public A(java.util.List arg0);
     0  aload_0 [this]
     1  invokespecial java.lang.Record() [47]
     4  aload_0 [this]
     5  aload_1 [arg0]
     6  putfield A.names : java.util.List [30]
     9  return
      Line numbers:
        [pc: 0, line: 1]

  Inner classes:
    [inner class info: #63 java/lang/invoke/MethodHandles$Lookup, outer class info: #65 java/lang/invoke/MethodHandles
     inner name: #67 Lookup, accessflags: 25 public static final]

Record: #Record
Components:
  
// Component descriptor #6 Ljava/util/List;
// Signature: Ljava/util/List<Ljava/lang/String;>;
java.util.List names;
Bootstrap methods:
  0 : # 59 invokestatic java/lang/runtime/ObjectMethods.bootstrap:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/TypeDescriptor;Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/invoke/MethodHandle;)Ljava/lang/Object;
	Method arguments:
		#1 A
		#60 names
		#61 REF_getField names:Ljava/util/List;
}
```

### PR DESCRIPTION
**Pull request by snjeza**
Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

Steps To Reproduce:

See https://github.com/eclipse/eclipse.jdt.ls/issues/2374#issue-1497690431

### CODE REVIEW

**Comment by snjeza** [comment]
@jarthana @mpalat I have fixed the failed test and added a new test.

**Comment by jarthana** [comment]
I have no issues with the patch, but just observed (looking at jdt code in general) that we use both `instanceof SyntheticMethodBinding` as well as` MethodBinding.isSynthetic().` I wonder if they are interchangeable.

**Comment by iloveeclipse** [comment]
@mpalat : any objections to merge this?

**Comment by mpalat** [comment]
> @mpalat : any objections to merge this?

Looks Good @iloveeclipse. Please go ahead and merge. Thanks

**Review by mpalat — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
