### PR TITLE
prepare SealedTypesTest for -Drun.javac=enabled

### PR DESCRIPTION
**Pull request by stephan-herrmann**
add test & excuse concerning [JDK-8343306](https://bugs.openjdk.org/browse/JDK-8343306)

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
@srikanth-sankaran fyi: with these additions I see SealedTypesTest passing even with:
```
-ea -Drun.javac=enabled -Djdk.root=/opt/java/jdk-23 -Dcompliance=23
```

I suggest we try to keep run.javac mode as clean as possible in those areas that we actively work on (even though the corresonding jenkins job is defunct).

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran fyi: with these additions I see SealedTypesTest passing even with:
> 
> ```
> -ea -Drun.javac=enabled -Djdk.root=/opt/java/jdk-23 -Dcompliance=23
> ```
> 
> I suggest we try to keep run.javac mode as clean as possible in those areas that we actively work on (even though the corresonding jenkins job is defunct).

Wonderful, Thanks.

**Comment by iloveeclipse** [comment]
> @srikanth-sankaran fyi: with these additions I see SealedTypesTest passing even with:
> 
> ```
> -ea -Drun.javac=enabled -Djdk.root=/opt/java/jdk-23 -Dcompliance=23
> ```
> 
> I suggest we try to keep run.javac mode as clean as possible in those areas that we actively work on (even though the corresonding jenkins job is defunct).

How long it takes? Could it be automated & run with every build?

**Comment by stephan-herrmann** [comment]
> How long it takes? 

Locally, SealedTypesTest takes ~ 4 seconds per compliance level, with runJava it's around 80 seconds.
So, I guess we can afford max a handful of such runs (test classes x compliance)  per regular build.

Note, that javac did not run on this PR build.

> Could it be automated & run with every build?

Back in the olden days, we had several timer triggered builds to run against different versions of javac. Over time the number of failures has eroded to an unmanageable pile of mud because nobody cared.

So for 23 I started to take stock for individual test classes, see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2212#issuecomment-2323293285

I'll try to provide the option for each test class to opt-in to this mode, but still need to figure out a few things:
* which javac to use?
   * should we continue to pass in the path to javac as a system property?
   * should we always pick javac from the version that is running the build?
* should per-test-class opt-in be always enabled, or
   * should javac be run only if globally enabled AND test class opts in?
   * should we add another system property to enable per-class opt-in?

@iloveeclipse given the noticeable execution time, should we
* select few test classes for every build, or
* create (resurrect) a dedicated build, to be run periodically (who will monitor it?)?

All this is said in the understanding that enabling this mode for the entire suite would be useless at this point.

**Comment by stephan-herrmann** [comment]
> Locally, SealedTypesTest takes ~ 4 seconds per compliance level, with runJavac it's around 80 seconds.

Assumeably, most of this time is spent launching a fresh javac process per test. If that's true than running javac in-process (via API) could significantly improve test performance. I don't have any experience with this API. Perhaps for @mickaelistria or @testforstephen this would be a piece of cake? :)

**Comment by stephan-herrmann** [comment]
@srikanth-sankaran some hints for test design: 
* testIssue2709() was not able to detect the recently confirmed difference between compilers, because we don't compare number of errors (too many secondary / optional errors would cause false positives in comparisons). We need black/white differences (fail/pass), that's way I'm adding the variant testJDK8343306()
* once we have confirmation about a javac bug it's easy to catalog this as in "excuse" like AbstractRegressionTest.JavacTestOptions.JavacHasABug.JavacBug8343306 
  * in BETA_JAVA24 I will then add the pivot version, capturing the fact that javac 24 will (probably) no longer have this bug.

**Comment by stephan-herrmann** [comment]
The following section of the console output demonstrates that javac comparison ran during https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-3204/4 :
```
[2024-10-31T15:25:11.593Z] org.eclipse.jdt.core.tests.compiler.regression.SealedTypesTests.testBug562715_001 - 23
[2024-10-31T15:25:11.593Z] ***************************************************************************
[2024-10-31T15:25:11.593Z] * Comparison with Sun Javac compiler for class SealedTypesTests (null tests)
[2024-10-31T15:25:11.593Z] ***************************************************************************
[2024-10-31T15:25:12.522Z] 
[2024-10-31T15:25:12.522Z] 
[2024-10-31T15:25:12.522Z] Full results sent to /tmp/comptest/run.1730387312395/23.0.1_20241031_151634.txt
[2024-10-31T15:25:12.522Z] org.eclipse.jdt.core.tests.compiler.regression.SealedTypesTests.testBug562715_002 - 23
[2024-10-31T15:25:13.454Z] 
[2024-10-31T15:25:13.454Z] 
[2024-10-31T15:25:13.454Z] Full results sent to /tmp/comptest/run.1730387312395/23.0.1_20241031_151634.txt
[2024-10-31T15:25:13.454Z] org.eclipse.jdt.core.tests.compiler.regression.SealedTypesTests.testBug562715_003 - 23
[2024-10-31T15:25:14.823Z] 
[2024-10-31T15:25:14.823Z] 
[2024-10-31T15:25:14.823Z] Full results sent to /tmp/comptest/run.1730387312395/23.0.1_20241031_151634.txt
[2024-10-31T15:25:14.823Z] org.eclipse.jdt.core.tests.compiler.regression.SealedTypesTests.testBug562715_004 - 23
[2024-10-31T15:25:15.755Z] 
[2024-10-31T15:25:15.755Z] 
[2024-10-31T15:25:15.755Z] Full results sent to /tmp/comptest/run.1730387312395/23.0.1_20241031_151634.txt
[2024-10-31T15:25:15.755Z] org.eclipse.jdt.core.tests.compiler.regression.SealedTypesTests.testBug562715_004a - 23
[2024-10-31T15:25:16.685Z] --- javac err: ---
[2024-10-31T15:25:16.685Z] X.java:6: warning: [rawtypes] found raw type: X
[2024-10-31T15:25:16.685Z] non-sealed class Y extends X {
[2024-10-31T15:25:16.685Z]                            ^
[2024-10-31T15:25:16.685Z]   missing type arguments for generic class X<T>
[2024-10-31T15:25:16.685Z]   where T is a type-variable:
[2024-10-31T15:25:16.685Z]     T extends Object declared in class X
[2024-10-31T15:25:16.685Z] 1 warning
[2024-10-31T15:25:16.685Z] 
[2024-10-31T15:25:16.946Z] 
[2024-10-31T15:25:16.946Z] 
[2024-10-31T15:25:16.946Z] Full results sent to /tmp/comptest/run.1730387312395/23.0.1_20241031_151634.txt
...
```

This particular test ran 4 min 15 sec. vs. 26 sec without javac comparison.

@iloveeclipse it seems, when we enable this for several test classes, build time will increase noticably. Is that OK for x times 4 min? Or should I put this behind another switch/system property, and enable it only for a dedicated build? Which one? Who will monitor it?

**Comment by stephan-herrmann** [comment]
OMG, those are still wasting resources once a week:
* https://ci.eclipse.org/jdt/job/eclipse.jdt.core-run.javac-1.8/
* https://ci.eclipse.org/jdt/job/eclipse.jdt.core-run.javac-10/
* https://ci.eclipse.org/jdt/job/eclipse.jdt.core-run.javac-12/

But: 
```
05:00:17 stderr: fatal: unable to connect to git.eclipse.org:
```
:sunglasses:

**Comment by stephan-herrmann** [comment]
For the question of automatically running tests in mode run.javac I re-opened https://github.com/eclipse-jdt/eclipse.jdt.core/issues/386 
@srikanth-sankaran  @iloveeclipse  please recommend there, how we should proceed.

---

For now I will disable run.javac even for the opt-in approach of SealedTypesTest, like this:
* `-Drun.javac=enabled` -> enable for entire suite
* `-Drun.javac=optin` -> enable only for test classes opting in via `AbstractCompilerTest.runJavacOptIn`
(will use equalsIgnoreCase() so nobody has to remember OptIn vs. opIn vs. optin :) ).

**Comment by testforstephen** [comment]
> > Locally, SealedTypesTest takes ~ 4 seconds per compliance level, with runJavac it's around 80 seconds.
> 
> Assumeably, most of this time is spent launching a fresh javac process per test. If that's true than running javac in-process (via API) could significantly improve test performance. I don't have any experience with this API. Perhaps for @mickaelistria or @testforstephen this would be a piece of cake? :)

Running javac as a standalone command line process and in-process each has its pros and cons. The standalone process offers more flexibility, as it can run with any javac version specified by the JDK path. In contrast, running in-process via the javac API is restricted to the Java runtime that initiates the unit test. I see the goal of `-Drun.javac` task is to compare ECJ result with any specified Javac version, keeping it as current approach is sensible. Given that this task primarily runs on the CI machine, the extra overhead is generally acceptable.

**Pull request merged**
