### PR TITLE
[tests] organize imports #2579

### PR DESCRIPTION
**Pull request by jukzi**
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2579

### CODE REVIEW

**Comment by jukzi** [comment]
@stephan-herrmann when is a good timepoint to submit this? Its purely the automatic cleanup (takes ~1min). As a second step we could then change the options. If beta branch is different it is possibly simpler to do the same refactoring there instead of solving merge conflicts if any.

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann when is a good timepoint to submit this? Its purely the automatic cleanup (takes ~1min). As a second step we could then change the options.

We should not leave much time between automatic cleanup and changing the options to avoid fresh drift between both actions. My preference: two commits (not-squashed) within one PR.

> If beta branch is different it is possibly simpler to do the same refactoring there instead of solving merge conflicts if any.

Generally I'd do such things only when there's only one writable branch. This will be guaranteed once the beta branch has been merged to master (around 17 September)

Alternatively, doing this in the beta branch is an interesting idea, but that would conflict with any other changes between Simrel GA and JDK 23 GA. We don't want to close master until the latter.

Also, the beta branch is under some stress until release, so probably better not to stir up unnecessary dust there right now.

So if you could hold your horses just 3 more weeks that would be safest :)

**Comment by stephan-herrmann** [comment]
On the positive side #2679 should help avoid that import changes result in warning changes :)

**Comment by jukzi** [comment]
looks like beta branch has been merged - ready for an update?

**Comment by stephan-herrmann** [comment]
> looks like beta branch has been merged - ready for an update?

indeed so - you're unblocked ...

**Comment by jukzi** [comment]
superseeded by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3032

**Pull request closed without merging**
