### PR TITLE
Test to see if I do something different to others

### PR DESCRIPTION
**Pull request by iloveeclipse**
Same commit as Stephan submitted in [PR](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/28), without anything else.

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
it's already beyond the freeze point.
Either you're lucky, or I'm blacklisted, or both ;)

**Comment by iloveeclipse** [comment]
@stephan-herrmann : you could try following: create new branch on top of master, cherry pick your commit and create new pr with that. I can only assume your original branch or its jenkins branch is somehow damaged.

**Comment by iloveeclipse** [comment]
@stephan-herrmann : or you can approve this PR and we merge that (that's your first commit). As you like.

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann : you could try following: create new branch on top of master, cherry pick your commit and create new pr with that. I can only assume your original branch or its jenkins branch is somehow damaged.

I did this to get one more data point on what might / might not make the difference. Branch name? Commit message? ...

OTOH, I get the feeling that #41 is a real thing, and it's just a flap of a butterfly's wings that decides whether it hits.

**Comment by stephan-herrmann** [comment]
"Hooray", https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-48/1 for #48 got timeout, too!

So I have three freezing scenarios (#28, #48 and a local maven run), against one successful scenario (#47) by @iloveeclipse - Each scenario consistently reproduces its respective behavior.

Go figure.

I'm starting to lean towards the blacklist theory, because:

- my cases ("it doesn't work and we don't know why") is bad but normal in software development
- @iloveeclipse 's case ("it works and we don't know why") is worst case!

**Comment by iloveeclipse** [comment]
Three builds here succeeded now.

@stephan-herrmann : please note, **all** my pr's I've started today (not just this three builds here) succeeded without any hang. I don't know if this is a luck, but I don't think it is just random.

**Comment by stephan-herrmann** [comment]
@iloveeclipse  could the order of suites be the difference:

1. org.eclipse.jdt.core.tests.model.AllJavaModelTestsTracing
2. org.eclipse.jdt.core.tests.dom.RunAllTestsTracing
3. org.eclipse.jdt.core.tests.RunFormatterTests
=> WORKS

1. org.eclipse.jdt.core.tests.RunFormatterTests
2. org.eclipse.jdt.core.tests.dom.RunAllTestsTracing
=> FREEZE

One new mystery: why do different PRs invoke tests in different order (within the same test plug-in)?

Interesting input for #41 we seem to have a way to reproduce the problem!!

**Comment by stephan-herrmann** [comment]
abandoning after #48 succeeded (with a fix in test infra).

**Pull request closed without merging**
