### PR TITLE
Merge master into BETA_JAVA23

### PR DESCRIPTION
**Pull request by jarthana**
## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
**@jarthana it looks like this force-pushed killed some prior changes on BETA_JAVA23!!**

I happened to check for the changes from PR #2881

Could this have happened to other changes, too? How to figure out?

I found one interesting diff in https://github.com/eclipse-jdt/eclipse.jdt.core/compare/f37596e415196f39ac7bbf148e03ff68938537ed..17d4d2dfcaf62f120575753e1a6765530f84f37f#diff-8a6569d250cda98263a9f33412e161158a279fa6b9e4844afc474c3bee4ab083

Given that 17d4d2dfc is current HEAD in BETA_JAVA23 it looks like we lost even more changes, e.g., #2878 seems to be affected, too?

I locally still have my 0853e11ef5f1562e54a966f2889f48b23c3ce5ab from  #2881, will try to create a PR to restore all that was in there.

@jarthana , @mpalat  **Please don't merge to BETA_JAVA23 for the time being**, so my chances to restore lost changes are kept.

**Comment by jarthana** [comment]
Oh my. I was pretty sure, or so I thought, that I had pulled all the changes from the BETA_JAVA23. I have no idea how they went missing. I have no plans to do anything more on this. Please let me know if I can offer some help here.

**Comment by jarthana** [comment]
> Could this have happened to other changes, too? How to figure out?

This merge only brought in 4 commits and handful of changes to the BETA_JAVA23. Assuming your local BETA branch is still good, doing a comparison between this and your branch should tell us.

**Comment by stephan-herrmann** [comment]
The merge claims as its parent: 3756a1aaf543eaafa752af13c9d6a841325c0a6a

This dropped at least the following commits (quoted from a branch in my local clone):
* c336f18a0329f411ba33f67098a671423acc7ab8
* cbce8dd0dc8c652e8543c7d17489e79c6af05f98
* 498ccb4101c12c54228b50b408a1a8148a1f20b9
* 6b7f2848dc8981314881084bbb7d6c2569df8e83
* 2f5f013c2c97bd8ef0a32c8b6952de492aafe71f
* 0853e11ef5f1562e54a966f2889f48b23c3ce5ab

How can we find out if that list is complete? At least from the list of closed MRs, #2881 is indeed that latest on BETA_JAVA23 prior to the merge. Unfortunately, the merge of #2881 changed hashes wrt my local branch, so there's a tiny chance that my local branch is not exactly what we had on github, but so be it.

Here's my plan:
* in one local branch re-apply (cherry pick) the above commits in order
* in a second branch re-do merge from master on top of my latest in BETA_JAVA23
* compare both branches
  * if no significant changes found, I'll submit the former branch without squashing.
  * otherwise we'll scratch our heads

**Comment by jarthana** [comment]
> Here's my plan:
> 
>     * in one local branch re-apply (cherry pick) the above commits in order
>     * in a second branch re-do merge from master on top of my latest in BETA_JAVA23
>     * compare both branches
>       
>       * if no significant changes found, I'll submit the former branch without squashing.
>       * otherwise we'll scratch our heads

How about going with the latter? Assuming no change went into BETA since you last pulled, we are safer that way. Betting on my merge sounds flaky, imo.

**Comment by stephan-herrmann** [comment]
> Here's my plan:
> 
>     * in one local branch re-apply (cherry pick) the above commits in order

that's #2892

**Comment by stephan-herrmann** [comment]
> Here's my plan:
> 
> * [...]
> * in a second branch re-do merge from master on top of my latest in BETA_JAVA23

this merge succeeded without any conflicts
 
> * compare both branches

Git Tree Compare tells me: "No differences found ..." :+1:

**Comment by stephan-herrmann** [comment]
> > Here's my plan:
> > ```
> > * in one local branch re-apply (cherry pick) the above commits in order
> > * in a second branch re-do merge from master on top of my latest in BETA_JAVA23
> > * compare both branches
> >   
> >   * if no significant changes found, I'll submit the former branch without squashing.
> >   * otherwise we'll scratch our heads
> > ```
> 
> How about going with the latter? Assuming no change went into BETA since you last pulled, we are safer that way. Betting on my merge sounds flaky, imo.

The advantage of using your merge + cherry pick: that branch can be submitted without yet another force push.

The local comparison between both branches tells us we should have the best safety which my local branch can provide.

**Comment by stephan-herrmann** [comment]
As a second way of verifying I was going to check the number of tests run, but then I can't even find a single check linked from this PR, how is this possible?

**Comment by stephan-herrmann** [comment]
#2881 lists: "passed: 97274" - so that's the minimum we should reach also in #2892.

Did master introduce new tests in the relevant period?

**Comment by stephan-herrmann** [comment]
> Did master introduce new tests in the relevant period?

I believe this is the list of PRs from master going into the merge:
* #2820
* #2830
* #2702

@jarthana  can you confirm this list?

**Comment by jarthana** [comment]
> #2881 lists: "passed: 97274" - so that's the minimum we should reach also in #2892.
> 
> Did master introduce new tests in the relevant period?

I see two new tests in master (430761c7652b112749d58799d742d66366821820 and be7e2a9ef475e4d28ee1da573b18a0a34633c582)

**Comment by stephan-herrmann** [comment]
As of #2770 jenkins reported passed: 96524 -- this should be the last commit from the previous merge from master

As of #2702 we had passed: 96524, ups?

lesson learned: if the PR build was on top of old state in master, then it doesn't really tell us what I'm asking here ...

**Comment by stephan-herrmann** [comment]
Trying a different route:
* https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/master/341/ (for  #2770) : 96,524 tests
* https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/master/347/ (for #2702): 96,530 tests

6 additional tests (including tests run at multiple compliance levels)

Do PR builds and master builds use the same set of compliance levels?

**Comment by jarthana** [comment]
> Do PR builds and master builds use the same set of compliance levels?

Probably not. I see far fewer number on the I build.

**Comment by stephan-herrmann** [comment]
> Do PR builds and master builds use the same set of compliance levels?

PR build (master): 

> Probably not. I see far fewer tests on the I build.

I wasn't referring to I-build but to https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/master/

**Comment by jarthana** [comment]
I see five instances of testMissingClass_varargs4_noArg ([here](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/master/347/testReport/org.eclipse.jdt.core.tests.compiler.regression/ProblemTypeAndMethodTest/)) and one instance of other. So, 6 accounted for.

**Comment by stephan-herrmann** [comment]
https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2892/1/testReport/ : 97,280 tests

[Previous on beta](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2888#issuecomment-2326148218): passed: 97274

Expected increase: 6

Expected total: 97280

@jarthana I'll retrigger jenkins until we're free from intermittent failures.

Please confirm that this can be submitted once we have a green build.

**Comment by jarthana** [comment]
Failed again with a different test in the same suite. Kicked off again. Let's see if third time's lucky.

**Pull request merged**
