### PR TITLE
Increase bundle versions of split package org.eclipse.jdt.annotation

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3027

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
Frankly, I'm not a fan of simulating "activity" of a bundle with no active maintenance for some time already.

To remove the dependency in our test bundles I just filed #3029 - after that it should be safe to stop building the bundle altogether.

**Comment by stephan-herrmann** [comment]
> To remove the dependency in our test bundles I just filed #3029 - after that it should be safe to stop building the bundle altogether.

After resolving #3029 only these locations still reference to org.eclipse.jdt.annotation_v1:
* org.eclipse.jdt.ui.tests: MANIFEST.MF
* the JDT feature

**Comment by merks** [comment]
FYI, both appear to have new qualifiers and hence both have new signatures:

image

But only one has a new minor version so only one will be published to Maven Central for the upcoming release...

**Comment by stephan-herrmann** [comment]
> After resolving https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3029 only these locations still reference to org.eclipse.jdt.annotation_v1:
> * org.eclipse.jdt.ui.tests: MANIFEST.MF

https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1712 is stuck with seemingly unrelated test failure.

**Comment by stephan-herrmann** [comment]
> After resolving #3029 only these locations still reference to org.eclipse.jdt.annotation_v1:
> * ...
> * the JDT feature

this is https://github.com/eclipse-jdt/eclipse.jdt/pull/118

**Comment by stephan-herrmann** [comment]
> this is [eclipse-jdt/eclipse.jdt#118](https://github.com/eclipse-jdt/eclipse.jdt/pull/118)

merged.

Let's see if the next build still contains any traces of the 1.x version.

**Comment by stephan-herrmann** [comment]
> Let's see if the next build still contains any traces of the 1.x version.

I don't see it any more.  Closing this PR.

**Pull request closed without merging**
