### PR TITLE
Removed dependencies to removed JDT fragments

### PR DESCRIPTION
**Pull request by iloveeclipse**
- org.eclipse.jdt.compiler.apt
 - org.eclipse.jdt.compiler.tool

See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/181

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Any help fixing apt tests would be appreciated...

**Comment by akurtakov** [comment]
My guess is that the the new bundle doesn't register javax.tools.JavaCompiler properly.

**Comment by akurtakov** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/blob/457e2221c44b49b6f38fcdfe6d1d59467a04bf75/org.eclipse.jdt.compiler.apt.tests/META-INF/MANIFEST.MF#L21 is optional but this is where the service class lives so it doesn't look optional to me. What do you think about trying to change it?

**Comment by iloveeclipse** [comment]
> What do you think about trying to change it?

Let see if the next attempt fixes tests. The service definition was for whatever reason **manually** copied to the build jar in one of the ant scripts. I guess because it was in a fragment. OMFG.

**Comment by iloveeclipse** [comment]
> My guess is that the the new bundle doesn't register javax.tools.JavaCompiler properly.
> Edit: I am wrong.

That **was** the case. Why do you think you were wrong?

**Comment by akurtakov** [comment]
> That **was** the case. Why do you think you were wrong?
```
Iterator<JavaCompiler> iter =ServiceLoader.load(JavaCompiler.class).iterator();
		while(iter.hasNext()) {
			JavaCompiler compiler = iter.next();
			System.out.println(compiler);
		}
```
with the jar produced by maven for the new bundle gave me both javac and ecj.

**Pull request merged**
