### PR TITLE
Force signing of split package bundles to use new certificate

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2044

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Ed, you seem to have now two commits with the merge commit

**Comment by merks** [comment]
@iloveeclipse 

Yes, I'm not sure what I did wrong, but I tried to correct it...

**Comment by iloveeclipse** [comment]
I've just merged one outstanding PR, so please rebase now.

**Comment by merks** [comment]
I changed the button to rebase and pushed it, so I think it's good/better now. 

As always, THANK YOU FOR YOUR TIRELESS DEDICATION.  Enjoy your well deserved week without a computer!!  👼

**Review by iloveeclipse — APPROVED** [review]

**Comment by iloveeclipse** [comment]
Thank you Ed.

**Pull request merged**
