### PR TITLE
Revert https://github.com/eclipse-jdt/eclipse.jdt.core/pull/630

### PR DESCRIPTION
**Pull request by srikanth-sankaran**
## What it does

Revert https://github.com/eclipse-jdt/eclipse.jdt.core/pull/630 for the time being as it results in a cascade of issues

## Author checklist

- [ ] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
We have two distinct failures in NullTypeAnnotationTests (multiplied by compliance levels):
* testGH854
I'm not much surprised [see here](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/854#issuecomment-1553547551), but will have a second look shortly
* testBug522142_bogusError
This might indeed indicate that [#683](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/683) needs [#630](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/630) - I'm looking into this now

**Comment by stephan-herrmann** [comment]
Analysis for testBug522142_bogusError, with this example code:
```
@NonNullByDefault({PARAMETER, RETURN_TYPE, FIELD, TYPE_PARAMETER, TYPE_BOUND, TYPE_ARGUMENT})
	interface Foo<A> {
		interface Bar<A> extends Iterable<Foo<A>> {
	}
}
```

After Foo<A> has been correctly translated into Foo<`@NonNull` A> (due to `@NNBD`), it's the member type Bar\<A> where the reference "Foo\<A>" is resolved before the type parameter \<A> (declared by Bar) has applied the nullness default. Note that `@NNBD` should apply only to the declaration of A, not to its application.

Yet, the bound check for the `PSTR` Foo\<A> is deferred, for now its resolved type has no nullness information.

"Belatedly", `resolveAnnotations` on the same `PSTR` triggers `evaluateNullAnnotations` for `MTB` Bar, where Bar's \<A> is translated to \<`@NonNull` A>.

`connectTypeHierarchy` finishes without finding any problem.

Fast-forward to `CUS.checkParameterTypes()` and into `CS.checkParameterizedTypeBounds()` for the member Bar: we need to check the `PST` for Foo\<A>, which still has no nullness information. At this point, the type to check against is "Foo\<`@NonNull` A>". This is were we report that "The type 'A' is not a valid substitute for the type parameter '`@NonNull` A'"

Ergo: yes, this test from #854 requires additional help either from #630 or from #1077. But ... (tbc)

**Comment by stephan-herrmann** [comment]
> Point-fix for NullTypeAnnotationTest.testBug522142_bogusError() in #1079 in absence of #630.

This is the most careful thing I can think of for 4.28. @srikanth-sankaran  WDYT?

> Disable testGH854 to enable running of more test suites

I think that test is dispensable for now, but I'll take another look as promised.

**Comment by stephan-herrmann** [comment]
>>    Disable testGH854 to enable running of more test suites
>
> I think that test is dispensable for now, but I'll take another look as promised.

The failure is caused in the exact code location where [my first attempt](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/c5bf8ba462db157a983c5d2c0e6ce25900897145) of #1067 introduced a lot of new scaffolding to ensure an auspicious order of event. I think adding such stuff on top of this revert commit would be too much.

**Comment by srikanth-sankaran** [comment]
> > Point-fix for NullTypeAnnotationTest.testBug522142_bogusError() in #1079 in absence of #630.
> 
> This is the most careful thing I can think of for 4.28. @srikanth-sankaran WDYT?
> 
> > Disable testGH854 to enable running of more test suites
> 
> I think that test is dispensable for now, but I'll take another look as promised.

Looking into this ...

**Comment by iloveeclipse** [comment]
> we can proceed to merge this - after project lead approval

Please do! Thank you both!

**Pull request merged**
