### PR TITLE
[Patterns]  Alternate, simpler pattern binding management implementation

### PR DESCRIPTION
**Pull request by srikanth-sankaran**
## What it does

Reimplements pattern resolution and pattern binding management in a much simpler design.
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1884
* Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1887

## Author checklist

- [ ] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by srikanth-sankaran** [comment]
The change to org.eclipse.jdt.core.tests.compiler.regression.RecordPatternTest.testIssue900_3() needs some more checking. I think it is correct and that on master there is some weird stuff going on - the method `org.eclipse.jdt.internal.compiler.ast.RecordPattern.resolveType(BlockScope, boolean)` get called more than once and against identical invocation `this.type.resolveType(scope);` returns null the first time and a valid binding the second time!!!

**Comment by srikanth-sankaran** [comment]
Jay, I expect the tests to be green, please review and do a bit of stress testing. I am happy to discuss the changes or walk you through

**Comment by srikanth-sankaran** [comment]
> Jay, I expect the tests to be green, please review and do a bit of stress testing. I am happy to discuss the changes or walk you through

@jarthana, tests finished green and can be reviewed. I have after some thought, deferred lots of refactoring changes into a separate PR to make it easier to review this.

(such as:

`getPatternVariablesWhenTrue()` --> `variablesWhenTrue()`
`getPatternVariablesWhenFalse()` --> `variablesWhenFalse()`
`getPatternVariablesLiveUponCompletion()` --> `variablesWhenComplete()`
`resolveWithPatternVariablesInScope()` --> `resolveWithVariables()`
`AccPatternVariable` ---> `OutOfFlowScope`  (a pattern binding starts being out of scope, when definitely assigned this bit is cleared - makes for more readable code - than clearing AccPatternVariable - it is not as though a pattern variable ceases to be a pattern variable ever - so clearing this bit is not aesthetic) etc

**Comment by srikanth-sankaran** [comment]
Notes to self: Further clean up may be possible in ForeachStatement, ForStatement and LocalDeclaration,

**Review by jarthana — APPROVED** [review]
Patch looks good. I appreciate that we could get rid of the collectPatternVariablesToScope() which has been a source of gaps in implementation.

**Comment by srikanth-sankaran** [comment]
Thanks Jay!

**Pull request merged**
