### PR TITLE
Check for record superclass before generic type

### PR DESCRIPTION
**Pull request by cart-before-horse**
## Check for record superclass before generic type in BinaryTypeBinding
Supposedly fixes the issue https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1497 , unit test is included

The best i could think of is just rearrange checks so java.lang.Record is being detected no matter generic type
I'm not entirely sure if this is a proper solution - apart from this particular scenario, record modifier is set even if there is generic interface. I tried a bunch of similar yet working cases and it seems like record modifier ends up in binding either from this check, or just inherited from package modifiers in constructor https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/BinaryTypeBinding.java#L321
Maybe real problem lies somewhere deeper, like inner classes resolution order or something.

## How to test
Run `org.eclipse.jdt.core.tests.compiler.regression.RecordsRestrictedClassTest#testBugGH1497readFromRecordWithGenericInterface` test
It is in separate commit so it's easy to debug current implementation without any fixes

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by srikanth-sankaran** [comment]
I offer to review this and take it forward. 

Looks like you haven't signed Eclipse Contributor agreement - Can you look into signing it please ? 

Information should be available here: https://www.eclipse.org/legal/ECA.php and here: https://www.eclipse.org/legal/committer_process/re-sign/

**Comment by cart-before-horse** [comment]
@srikanth-sankaran Hi, thanks for the reply!

Is ECA necessary? I just want the IDE to work properly, if anything, i would like not to reveal my personal data to yet another website because of one bugfix worth of 20 lines of code.
In case its crucial, feel free to take over this PR, resign commits, or whatever, i dont mind at all.

**Comment by srikanth-sankaran** [comment]
@cart-before-horse I double checked with the component lead to confirm
ECA is needed. The wise elders have formulated the processes after due consideration of the factors involved I would think. So accepting contributions without ECA in place will truly be putting the cart before the horse 😂 pun intended. 

And Eclipse/GitHub is not any other website - but I acknowledge and respect your right and prerogative to not do the ECA. 

I'll take over this defect and take it forward as per your wish. 

Thanks for reporting the problem and your analysis.

**Comment by srikanth-sankaran** [comment]
This PR is superseded by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1552

**Comment by srikanth-sankaran** [comment]
> ## Check for record superclass before generic type in BinaryTypeBinding
> Supposedly fixes the issue #1497 , unit test is included
> 
> The best i could think of is just rearrange checks so java.lang.Record is being detected no matter generic type I'm not entirely sure if this is a proper solution - apart from this particular scenario, record modifier is set even if there is generic interface. I tried a bunch of similar yet working cases and it seems like record modifier ends up in binding either from this check, or just inherited from package modifiers in constructor https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/BinaryTypeBinding.java#L321 Maybe real problem lies somewhere deeper, like inner classes resolution order or something.
> 
> ## How to test
> Run `org.eclipse.jdt.core.tests.compiler.regression.RecordsRestrictedClassTest#testBugGH1497readFromRecordWithGenericInterface` test It is in separate commit so it's easy to debug current implementation without any fixes
> 
> ## Author checklist
> * [x]  I have thoroughly tested my changes
> * [x]  The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
> * [x]  I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

See the comment in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1497 that explains why this problem shows up only for inner records

**Pull request closed without merging**
