### PR TITLE
Add support for array constructor reference :#583

### PR DESCRIPTION
**Pull request by gayanper**
## What it does
This change will provide new completion entry for method references on a array type reference.

## How to test
use the following code snippet `Arrays.asList("1").stream().toArray(String[]::)`

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by gayanper** [comment]
Since this is a small change, I would like to merge it if @jarthana and @stephan-herrmann doesn't see any thing that should be done differently.

**Comment by gayanper** [comment]
@testforstephen would you be able to have a look at this until others provide their feedbacks

**Comment by testforstephen** [comment]
@gayanper It makes sense to auto suggest array constructor for method reference expression. What do you think if we also support autocompleting all Object methods?

image

**Comment by gayanper** [comment]
> @gayanper It makes sense to auto suggest array constructor for method reference expression. What do you think if we also support autocompleting all Object methods?
> 
> image

Do you see any value with such suggestion as a method reference ?

**Comment by testforstephen** [comment]
> Do you see any value with such suggestion as a method reference ?

I see other IDE like IJ provides a full list of methods there. Yes, the array constructor is the most frequently used for me as well. If the ROI is not worth it, it's good to me to only suggest `new` method.

**Comment by gayanper** [comment]
> > Do you see any value with such suggestion as a method reference ?
> 
> I see other IDE like IJ provides a full list of methods there. Yes, the array constructor is the most frequently used for me as well. If the ROI is not worth it, it's good to me to only suggest `new` method.

If you don't see any issues in the implementation I would like to merge this.

**Comment by iloveeclipse** [comment]
@gayanper : could sou please squash commits to ome and avoid merge commits?

**Review by testforstephen — APPROVED** [review]
LGTM

**Pull request merged**
