### PR TITLE
UI Freezes since 2023-09

### PR DESCRIPTION
**Pull request by stephan-herrmann**
experimental fix for #1728

 disable annotation resolution / evaluation for some clients

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
This draft change (for performance reasons) quite drastically pulls the plug on any treatment of annotations when invoked from **codeSelect** or **codeComplete** or when a UI action requests a **type hierarchy**. More specifically all of the "new" phase `INTEGRATE_ANNOTATIONS_IN_HIERARCHY` will be skipped for all types except for the focus type (this logic being applied only on the `askForType()` -> `accept()` path).

@srikanth-sankaran could you think of any reasons why such use cases could **require** resolved information about annotations on referenced types? Here 'referenced' includes those referenced as supertypes of the focus type.

**Comment by stephan-herrmann** [comment]
@gigermocas would you be able to directly use this change for some testing? That would greatly help to find out:
* does the change improve performance?
* does it cause any regressions?

**Comment by gigermocas** [comment]
Yes, this a bit more manageable. Actively editing a source file and using content assist is snappy.

Trying to copy some text while editing the file still freezes and locks the UI, there seems to be some contention there ([trace.log](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14850124/trace.log)). I have to wait until the background compilation triggered by the file change completely stops, which takes several seconds. If there's no background compilation the copy operation is lighter there and by itself doesn't freeze the UI anymore.

I must admit I don't fully understand it, I would expect that copying some text should work regardless of background compilation, as triggering the content assist seems to be doing, does this make sense?

Otherwise I'm not seeing any other issues, I will daily drive this and report back if I see anything weird. Thanks!

**Comment by stephan-herrmann** [comment]
> Yes, this a bit more manageable. Actively editing a source file and using content assist is snappy.

thanks for your feedback! I'm glad my guess at a culprit was not completely off the mark! :)

> Trying to copy some text while editing the file still freezes and locks the UI, there seems to be some contention there ([trace.log](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14850124/trace.log)). I have to wait until the background compilation triggered by the file change completely stops, which takes several seconds. If there's no background compilation the copy operation is lighter there and by itself doesn't freeze the UI anymore.
> 
> I must admit I don't fully understand it, I would expect that copying some text should work regardless of background compilation, as triggering the content assist seems to be doing, does this make sense?

The connection here is, that `org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationAction` wants to add imports that are required to make the pasted code compilable. Computing these imports is what requires a resolved AST, which in turn requires access to workspace resources that could be locked by the build.

If you see room for improvement in this area please file a new issue for our brothers and sisters at eclipse.jdt.ui (with the latest log file attached)
 
> Otherwise I'm not seeing any other issues, I will daily drive this and report back if I see anything weird. Thanks!

Great, so I'll wait -- say -- one week for you to report back. If no new issues are observed, I'll go ahead an merge.

**Comment by gigermocas** [comment]
I'm noticing that the type hierarchy is also requested through trying to open the  "Run As"/"Debug As" menu ([stack.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14874554/stack.txt)), resulting in a freeze as well. Can annotation processing be disabled from there as well?

> The connection here is, that org.eclipse.jdt.internal.ui.javaeditor.ClipboardOperationAction wants to add imports that are required to make the pasted code compilable. Computing these imports is what requires a resolved AST, which in turn requires access to workspace resources that could be locked by the build.

I see, and that behavior I can actually disable in the editor typing preferences, good to know!

**Comment by stephan-herrmann** [comment]
> I'm noticing that the type hierarchy is also requested through trying to open the "Run As"/"Debug As" menu ([stack.txt](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14874554/stack.txt)), resulting in a freeze as well. Can annotation processing be disabled from there as well?

The stack only shows the initial `completeTypeBindings(CompilationUnitDeclaration[], boolean[], int) ` for which work on annotations are not (yet) suppressed, but this shouldn't matter, the bulk of the work is done only via `accept()` (for additional types). One of the `accept()` methods already has the short-circuit, will add it to a second one just now.

If you still observe slowness, look out for `integrateAnnotationsInHierarchy()`, that's the guy we are trying to avoid in the current experiment.

**Comment by gigermocas** [comment]
I got tripped up by that. The real culprit in this case is `org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.internalIsTest`, which requires a resolved AST ([trace.log](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14885933/trace.log)), this is something more like the copy with imports situation sadly.

**Comment by stephan-herrmann** [comment]
> The real culprit in this case is `org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.internalIsTest`, which requires a resolved AST

In this case the caller who knows what is needed (`JUnit5TestFinder`) is many stack levels away from `completeTypeBindings()` where I inserted the new flag. 

I suggest to postpone this for now. Once we are confident that the new flag does help (to some degree) and introduces no regressions, then we can think of ways to tell `ASTParser` or similar guys that annotations on super types are not of interest, so that clients like JUnit5TestFinder can simply opt-out.

**Comment by stephan-herrmann** [comment]
@gigermocas with one more confirmation from your side I'd be ready to merge. Did you observe any ill effects of the change? 

Further use cases where the same strategy could be applied can be taken up separately.

**Comment by gigermocas** [comment]
It's been working great here. I didn't encounter any related issues.

Regarding a more customizable AST parser, I hope you guys find that compelling enough to have a go at it. That would greatly improve the performance in the remaining areas.

**Pull request merged**
