### PR TITLE
Fix the require bundle version for compiler.batch

### PR DESCRIPTION
**Pull request by jarthana**
## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by jarthana** [comment]
@iloveeclipse Is this okay or do you think we should go for a range?

**Comment by iloveeclipse** [comment]
> Is this okay or do you think we should go for a range?

I honestly would like to uunderstand the problem first before discussing a solution :-)
Do we have a ticket describing the problem?

**Comment by jarthana** [comment]
> > Is this okay or do you think we should go for a range?
> 
> I honestly would like to uunderstand the problem first before discussing a solution :-) Do we have a ticket describing the problem?

The problem is, when I upped the version numbers for the BETA branch, I didn't update the bundle dependency version. Then someone pointed out that it is a tightly coupled to the current version and not a range. I am happy with just fixing the version, but just not sure if this tight dependency is intentional.

**Comment by iloveeclipse** [comment]
If I understand it right, jdt core should have strict dependency relationship with batch compiler. 
It can be a range too, but range should set minimal ecj version to latest "tested" one. On beta branch it should be also higher as on master, isn't?

**Comment by jarthana** [comment]
> If I understand it right, jdt core should have strict dependency relationship with batch compiler. It can be a range too, but range should set minimal ecj version to latest "tested" one. 

OK, actually on BETA, it makes no sense to have a different version. We added quite a few stuff in compiler.batch that will be used in jdt.core. So, looks like it's very unlikely we will ever have a range.

>On beta branch it should be also higher as on master, isn't?
We are going to be making patches for 4.27 off BETA branch. So, it only needs to be higher than 4.27 and preferably lower than master. Once we merge the BETA changes to master, we will bump the master anyway to 3.34 as there will be quite a few API changes.

**Comment by iloveeclipse** [comment]
> we will bump the master anyway to 3.34 as there will be quite a few API changes.

Should we do that on master now?

> I also noticed that in master we have 3.33.101 in jdt.core and 33.100 in compiler.batch.

This is a mistake, see https://github.com/eclipse-jdt/eclipse.jdt.core/pull/768

**Comment by jarthana** [comment]
> > we will bump the master anyway to 3.34 as there will be quite a few API changes.
> 
> Should we do that on master now?

We can if there are already API changes in master. Otherwise, since the Java GA (and hence the merge) is only a couple of days away, we can take it up at that time. I will shortly create a patch that needs to be pushed after the merge.

**Comment by ktatavarthi** [comment]
> If I understand it right, jdt core should have strict dependency relationship with batch compiler. It can be a range too, but range should set minimal ecj version to latest "tested" one. On beta branch it should be also higher as on master, isn't?

If ther is going to be a tightly coupled dependency between jdt.core and batch compiler, this information needs to be documented as som eplace so that who ever is updating the batch compiler version does not miss updating the version in  the dependencies of jdt.core

**Pull request merged**
