### PR TITLE
Add special handling for release 9 with JDK 12-

### LINKED ISSUE #539: release option 9 make compiler break when using JDK 11
original post can be found here: https://github.com/eclipse-m2e/m2e-core/issues/1065

If we have JDK 11 as environment and release option enabled with source level 9, then we will get the error: 
```
The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files
```

The issue can also be reproduced in JDK 10 with release 9, but disappear with 

- release 10+
- release 9-
- JDK 12+

Although we have a warning provided since https://bugs.eclipse.org/bugs/show_bug.cgi?id=544674, m2e will automatically add the release tag from pom.xml and the warning message has no opportunity to be found.

I found there was a patch to fix this issue in release 10: https://github.com/eclipse-jdt/eclipse.jdt.core/commit/8cf64302cf48ebc8b9e15908bc66f2358cbcccb9. Since the issue can be observed in release 9 as well, we should make a similar patch for this.

### PR DESCRIPTION
**Pull request by CsCherrYY**
Signed-off-by: Shi Chen <chenshi@microsoft.com>

## What it does

fix #539, add a special handing for release 9 with JDK 12-.

## How to test

use added test case `testConvertToModuleWithRelease9()`

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Review by testforstephen — APPROVED** [review]
LGTM. This is a straight-forward fix same as https://github.com/eclipse-jdt/eclipse.jdt.core/commit/8cf64302cf48ebc8b9e15908bc66f2358cbcccb9.

@iloveeclipse Could you help a review on this?

**Comment by iloveeclipse** [comment]
@CsCherrYY : would you please rebase you branch on master? Something like this should work:
`git rebase -s subtree master`

**Comment by CsCherrYY** [comment]
@iloveeclipse done in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/540/commits/c7eb15acf2f3fbaecc07a7c31056eb24aa3cc0db

**Comment by iloveeclipse** [comment]
> @iloveeclipse done in [c7eb15a](https://github.com/eclipse-jdt/eclipse.jdt.core/commit/c7eb15acf2f3fbaecc07a7c31056eb24aa3cc0db)

Thanks, I've rebased once again, added proper commit message and updated comment in the code.
LGTM now.

**Comment by CsCherrYY** [comment]
thank you @iloveeclipse !

**Pull request merged**
