### PR TITLE
Bug 562551 - content assist not working inside lambda expression

### PR DESCRIPTION
**Pull request by jarthana**

### CODE REVIEW

**Review by gayanper — APPROVED** [review]
LGTM, But i would like @stephan-herrmann review as well to see if i missed something. I will also take this PR for a test drive.

**Comment by iloveeclipse** [comment]
I'm currently trying to help Jay and Stephan to understand why their PR's are hanging...
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/38

While doing that, I've found #45 and that all opened PR's seem to be automatically rebuilt by Jenkins on every change in master branch. 

I **believe**, the PR's should be rebased in github on latest master (that has #45 merged) to avoid that crazy behavior.

It would be nice if @jarthana would do that now to verify my assumption, save our (jenkins) resources and may be prevent hangs for other PR's.

**Comment by stephan-herrmann** [comment]
This PR doesn't seem to reflect latest discussion in the original https://bugs.eclipse.org/562551 - @jarthana is your review request still relevant?

**Comment by jarthana** [comment]
> This PR doesn't seem to reflect latest discussion in the original https://bugs.eclipse.org/562551 - @jarthana is your review request still relevant?

No, it's not. I will revisit this later, whenever I can find some time.

**Comment by stephan-herrmann** [comment]
> No, it's not. I will revisit this later, whenever I can find some time.

@jarthana  feel free to re-request review when there's more here :)

**Comment by jarthana** [comment]
With @srikanth-sankaran back and working on lambdas again, I see no reason for myself to be messing around. IIRC, I don't think this was a complete fix. 

Srikanth, do you mind taking over https://bugs.eclipse.org/bugs/show_bug.cgi?id=562551 when you find time?

**Comment by srikanth-sankaran** [comment]
> With @srikanth-sankaran back and working on lambdas again, I see no reason for myself to be messing around. IIRC, I don't think this was a complete fix.

@srikanth-sankaran is back, but he hasn't been working on lambdas 😆 
> 
> Srikanth, do you mind taking over https://bugs.eclipse.org/bugs/show_bug.cgi?id=562551 when you find time?

No problem, it may be a while but I have been meaning to revisit this space. So, sure.

**Pull request closed without merging**
