### PR TITLE
Bug 576806 - Record components prevent undocumented empty block warning

### PR DESCRIPTION
**Pull request by MaisiKoleni**
## What it does

Empty record declarations are not reported as undocumented empty block if at least one record component is present.
This PR fixes the issue by requiring no record components to be present for a type declaration to be empty.

Note: This was previously https://git.eclipse.org/r/c/jdt/eclipse.jdt.core/+/191077

## How to test

For reproduction and reasoning, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=576806.
The existing and the newly added tests should cover this. To be precise, the new test checks that only a record with no record components and no content in the body triggers the warning, and that a record with record components or a comment is not considered an empty block.

## Author checklist

- I have thoroughly tested my changes
- The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by MaisiKoleni** [comment]
The build says:
> Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:3.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jdt.core: Only qualifier changed for (org.eclipse.jdt.core/3.30.0.v20220607-1645). Expected to have bigger x.y.z than what is available in baseline (3.30.0.v20220524-1333)

and
> No test report files were found. Configuration error?

I don't think this is related to my changes? Locally, the changes work in a fresh Eclipse IDE for Eclipse Committers - JDT setup.

**Comment by MaisiKoleni** [comment]
@sravanlakkimsetti done

**Comment by jubax** [comment]
It would be great if this PR could be merged so that it is available in the September release 👍

**Pull request closed without merging**
