### PR TITLE
Make Util.getSignature() handle NameQualifiedType

### PR DESCRIPTION
**Pull request by mickaelistria**
## What it does

Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1980

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by akurtakov** [comment]
Would you please add test about that? It should go in https://github.com/eclipse-jdt/eclipse.jdt.core/blob/master/org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/UtilTests.java . There are no tests for getSignature AFAICS but we have to start with some.

**Comment by mickaelistria** [comment]
> Would you please add test about that? 

Sure. Done.

**Review by akurtakov — APPROVED** [review]
That's pretty safe fix from what I can say.

**Comment by mickaelistria** [comment]
Thank you!

**Pull request merged**
