### PR TITLE
StackOverflowError on autocomplete imports on modular projects

### PR DESCRIPTION
**Pull request by iloveeclipse**
Converts recursive module dependencies search into stack based.

Fixes https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2169

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@stephan-herrmann, @mpalat : this is the fix for the fix in c43bada8f824033f76fd2417f54d46b6a0eb569e.

It is a draft as I don't have a test case and not familiar enough with the modules in order to construct one.

From the https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2169 issue I assume either the javafx contributes lot of extra modules with extra dependencies that simply overflow the (limited) stack size, or they contain circular dependencies (however I've assumed that shouldn't be possible due the spec).

I believe the change itself is straight forward, with the hashcode/equals added to the `org.eclipse.jdt.internal.core.ModuleDescriptionInfo.ModuleReferenceInfo` that isn't considering "super" fields as they aren't used at all while constructing `ModuleReferenceInfo` instances.

Would be nice if you could review that .

**Comment by iloveeclipse** [comment]
@stephan-herrmann, @mpalat : any objections merging this?

**Comment by stephan-herrmann** [comment]
I'm looking into this, trying to come up with a test.

**Comment by stephan-herrmann** [comment]
@iloveeclipse the fix is good essentially. Still I chose to create a new PR #2358 with a reduced version of your fix:
* keep the added `equals()` and `hashCode()` methods (although no other type in that hierarchy has them)
* keep collecting visited references and refuse to traverse any reference more than once
* OTOH I reverted to the recursive style, which IMHO is more direct and shouldn't hurt since the depth of any real life module graph should never come near creating a problem wrt stack size.

The good news: my test can demonstrate both problems:
* even in a "good" module graph, the same module may be reachable via many paths, causing (a lot of) redundant work
  * there is no assert for this, but just an added log statement easily demonstrates this
* adding a module cycle (though causing a compile error) would not stop completion to try going in cycles infinitely, i.e., the test succeeds in overflowing the stack when the fix is removed

**Comment by iloveeclipse** [comment]
With https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2358 we can close this one. Thanks @stephan-herrmann !

**Pull request closed without merging**
