### PR TITLE
[performance] less calls to isInModuleDeclaration() #1747

### PR DESCRIPTION
**Pull request by jukzi**
Reorder costly conditions

https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1747

### CODE REVIEW

**Review by srikanth-sankaran — CHANGES_REQUESTED** [review]
Why don't we pull up the token check to the call site ?? As pointed out earlier every other maybe* method is called after the token check. 

The way it stands now we will still make gazillion trips into maybeAtCasePattern although each call is faster now. 

I am making more of a consistency argument than a performance argument here. The patch may have solved the performance problem.

**Comment by jukzi** [comment]
> Why don't we pull up the token check to the call site ??

i did it to avoid code duplication:
image

**Comment by jukzi** [comment]
> The way it stands now we will still make gazillion trips into maybeAtCasePattern although each call is faster now.

if that is a hotspot typically the hotspot compiler would inline the method. I would not make assumptions that it is a problem just by looking at the code.

**Comment by srikanth-sankaran** [comment]
Ok. I would have preferred the checks being hoisted even if into two places but I can live with what you have proposed. Please proceed.

**Comment by srikanth-sankaran** [comment]
> > The way it stands now we will still make gazillion trips into maybeAtCasePattern although each call is faster now.
> 
> 
> 
> if that is a hotspot typically the hotspot compiler would inline the method. I would not make assumptions that it is a problem just by looking at the code.

Let us say hypothetically that it is a hotspot. The code being inlined into the call sites would be the wrong optimization imo but we don't have to argue that 😊

**Review by srikanth-sankaran — APPROVED** [review]

**Pull request merged**
