### PR TITLE
Update bundle and API versions after merge of BETA_JAVA21

### PR DESCRIPTION
**Pull request by jarthana**
## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by iloveeclipse** [comment]
There are few API errors.

**Comment by iloveeclipse** [comment]
I assume you are using 4.28 as API baseline?
What I see is:
image

**Comment by jarthana** [comment]
> I assume you are using 4.28 as API baseline? 

The baseline was fine, but I just forgot that I was testing the associated target platform with the Java 21 patches :(
Should be fine this time.

**Comment by iloveeclipse** [comment]
Yes, I do not see API errors anymore. Let see if tests will be happy too...

**Pull request merged**
