### PR TITLE
Rename "UnnamedClass" to "ImplicitlyDeclaredClass"

### LINKED ISSUE #2219: Use "Implicitly declared class" instead of unnamed class consistently
Throughout the codebase, we use both names interchangeably. It would be nice to stick to one. I think we should use "implicitly declared class", since that's the name from the newest JEP for the feature.

I am interested in making a PR for this

### PR DESCRIPTION
**Pull request by datho7561**
## What it does
Renames `UnnamedClass` to `ImplicitlyDeclaredClass` so that we consistently use `ImplicitlyDeclaredClass` to refer to the preview feature that allows writing `main(String... args)` methods without enclosing them in `class ClassName { ... }`.

Closes #2219

## How to test
This change should only be a renaming.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by datho7561** [comment]
@rgrunber @srikanth-sankaran if you have a chance, could you please take a look at this PR? I think it's a good idea to get this merged before anyone starts consuming `UnnamedClass.java`.

**Comment by rgrunber** [comment]
I noticed some places in `Parser`, `ASTConverter` & `JavaSearchBugs21Tests` that would still reference "UnnamedClass" in some way (variable name, method decl, etc.). Is that ok for now ?

Only reference in JDT UI I found was https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/3dcac4d1ce5540796481b030e434bb16e2a4bfde/org.eclipse.jdt.core.manipulation/core%20extension/org/eclipse/jdt/internal/corext/dom/HierarchicalASTVisitor.java#L167-L175 .

**Comment by datho7561** [comment]
Good catch! I'll go through the codebase a bit more thoroughly.

**Comment by datho7561** [comment]
@rgrunber when you have some time, could you please take another look at this PR?

**Comment by rgrunber** [comment]
What about references like https://github.com/eclipse-jdt/eclipse.jdt.core/blob/c995bab2842102ecbef40a5128aafdd2a47c472d/org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/messages.properties#L78 ?

image . Otherwise, I think the change is fine. Just have to be prepared to also update JDT UI.

**Comment by datho7561** [comment]
Good catch! I'll make sure to get that first thing Tueday

**Comment by rgrunber** [comment]
I'm fine with merging, but just be aware that things like https://github.com/eclipse-jdt/eclipse.jdt.core/blob/e53e413aadf6b0eab0f2867cc5b43c1420258512/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/ASTNode.java#L1110-L1115 might be a pain to rename after release.

**Review by rgrunber — APPROVED** [review]

**Comment by rgrunber** [comment]
@datho7561 you can probably also adjust JDT-UI to the new API. As soon as this hits the I-builds, classes in https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/ff344b7d85407169bea373df350ca14b0c95ac23 will fail.

**Comment by datho7561** [comment]
I'll work on adapting JDT-UI

**Pull request merged**
