### PR TITLE
organize imports #2579

### PR DESCRIPTION
**Pull request by jukzi**
enabled organize imports and automated cleanup

https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2579

### CODE REVIEW

**Comment by jukzi** [comment]
ignoring random fails and merging before likely mergeconflicts happen

**Comment by stephan-herrmann** [comment]
I beg your pardon, you are changing 1650 files, request a review and can't hold your horses waiting for the review? Do you expect a voluntary committer to react to your request on the same day, perhaps same hour, no matter what his job might require from him?

What makes you so sure that there is absolutely no problem in this commit?

I'm sure there are better ways to minimize merge conflicts.

**Comment by stephan-herrmann** [comment]
Please also coordinate with @jarthana  wrt BETA_JAVA24, since you actually missed the window where we had only one active branch.

**Comment by jarthana** [comment]
The BETA branch hasn't yet evolved, but I do have changes in my PR. So, I guess that'll have to deal with the merge conflicts. :(
Let's see how that goes.

**Pull request merged**
